import React from 'react';
import type { SecretaryVerwaltungTabProps } from './SecretaryVerwaltungTab';
import {
  parseRoomName,
  getFloorColor,
  getAlphabeticalColor,
  getAlphabeticalUniColor
} from '../utils/secretaryFormatters';

export interface BuildSecretaryVerwaltungPropsParams {
  // Identity & Core Infrastructure
  schoolId: string;
  schoolNumericId: number;
  userId?: string;
  supabase: any;
  currentSchoolProfile: any;
  setCurrentSchoolProfile: React.Dispatch<React.SetStateAction<any>> | ((profile: any) => void);
  currentUserProfile: any;
  showRealNames?: boolean;

  // Pricing & Accounting
  masterPricing: any;
  effectiveSchoolRates: any;
  masterRates: any;

  // Navigation & Shell
  navigation: any;

  // Teachers (State from SecretaryDashboard)
  campusTeachers?: any[];
  bypassTeachers?: any[];
  coaches?: any[];
  allTeachers?: any[];

  // Rooms & State from SecretaryDashboard
  rooms?: any[];
  setRooms?: React.Dispatch<React.SetStateAction<any[]>>;
  roomSearchQuery?: string;
  setRoomSearchQuery?: React.Dispatch<React.SetStateAction<string>> | ((query: string) => void);
  userMap?: Record<string, string>;
  isAvvSigned?: boolean;
  setShowAvvModal?: React.Dispatch<React.SetStateAction<boolean>> | ((val: boolean) => void);
  simulatedToday?: string;
  setSimulatedToday?: React.Dispatch<React.SetStateAction<string>> | ((val: string) => void);
  dismissedInvoiceAlert?: boolean;
  setDismissedInvoiceAlert?: React.Dispatch<React.SetStateAction<boolean>> | ((val: boolean) => void);

  // Hook Bundles
  settings: any;
  extendedSettings: any;
  licenses: any;
  staff: any;
  studentsHook: any;
  bookings: any;
  schedules: any;
  equipment: any;
  announcements: any;
  audit: any;
  crisis: any;
  dashboardData: any;

  // View States & Overrides
  roomsSubView: any;
  setRoomsSubView: any;
  schedulesRoomsViewMode: any;
  setSchedulesRoomsViewMode: any;
  onOpenFacilityLogModal?: () => void;
  setIsFeedbackModalOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setShowDpoIdCardModal: React.Dispatch<React.SetStateAction<boolean>>;
  setShowDpoPortalModal: React.Dispatch<React.SetStateAction<boolean>>;
  setQrModalUser: (user: any) => void;
  getEffectiveStorageUsedBytes: (profile: any) => number;
  formatInstrumentName: (name?: string | null | any) => string;
  checkTimeOverlap: (t1Start: string, t1End: string, t2Start: string, t2End: string) => boolean;
}

/**
 * Builds the complete, type-safe prop tree for SecretaryVerwaltungTab
 * reducing prop sprawl in SecretaryDashboard.tsx while maintaining Goldstandard isolation.
 */
export function buildSecretaryVerwaltungProps(
  params: BuildSecretaryVerwaltungPropsParams
): SecretaryVerwaltungTabProps {
  const {
    schoolId,
    schoolNumericId,
    userId,
    supabase,
    currentSchoolProfile,
    setCurrentSchoolProfile,
    currentUserProfile,
    masterPricing,
    effectiveSchoolRates,
    masterRates,
    navigation,
    settings,
    extendedSettings,
    licenses,
    staff,
    studentsHook,
    bookings,
    schedules,
    equipment,
    announcements,
    audit,
    crisis,
    dashboardData,
    roomsSubView,
    setRoomsSubView,
    schedulesRoomsViewMode,
    setSchedulesRoomsViewMode,
    onOpenFacilityLogModal,
    setIsFeedbackModalOpen,
    setShowDpoIdCardModal,
    setShowDpoPortalModal,
    setQrModalUser,
    getEffectiveStorageUsedBytes,
    formatInstrumentName,
    checkTimeOverlap
  } = params;

  return {
    secretarySubTab: navigation.secretarySubTab,
    setSecretarySubTab: navigation.setSecretarySubTab,
    activeTab: navigation.activeTab,
    setActiveTab: navigation.setActiveTab,
    campusSubTab: navigation.campusSubTab,
    setCampusSubTab: navigation.setCampusSubTab,
    schoolId,
    schoolNumericId,
    schoolName: settings.schoolName,
    schoolStreet: settings.schoolStreet,
    setSchoolStreet: settings.setSchoolStreet,
    schoolHouseNumber: settings.schoolHouseNumber,
    setSchoolHouseNumber: settings.setSchoolHouseNumber,
    schoolZipCode: settings.schoolZipCode,
    setSchoolZipCode: settings.setSchoolZipCode,
    schoolCity: settings.schoolCity,
    setSchoolCity: settings.setSchoolCity,
    schoolSubdomain: settings.schoolSubdomain,
    setSchoolSubdomain: settings.setSchoolSubdomain,
    schoolPhoneNumber: settings.schoolPhoneNumber,
    setSchoolPhoneNumber: settings.setSchoolPhoneNumber,
    schoolEmail: settings.schoolEmail,
    setSchoolEmail: settings.setSchoolEmail,
    absenceEmail: settings.absenceEmail,
    setAbsenceEmail: settings.setAbsenceEmail,
    logoUrl: settings.logoUrl,
    setLogoUrl: settings.setLogoUrl,
    setSchoolName: settings.setSchoolName,
    currentSchoolProfile,
    setCurrentSchoolProfile,
    currentUserProfile,
    userId,
    supabase,
    windowWidth: navigation.windowWidth,
    fetchDashboardData: dashboardData.fetchDashboardData,

    // Rooms & Allocation
    rooms: params.rooms ?? dashboardData?.rooms ?? [],
    setRooms: params.setRooms ?? dashboardData?.setRooms ?? (() => {}),
    buildings: dashboardData?.buildings ?? [],
    setBuildings: dashboardData?.setBuildings ?? (() => {}),
    matrixAllocations: schedules?.matrixAllocations ?? [],
    roomSearchQuery: params.roomSearchQuery ?? dashboardData?.roomSearchQuery ?? '',
    setRoomSearchQuery: params.setRoomSearchQuery ?? dashboardData?.setRoomSearchQuery ?? (() => {}),
    selectedDayPlan: schedules?.selectedDayPlan,
    setSelectedDayPlan: schedules?.setSelectedDayPlan,
    roomsSubView,
    setRoomsSubView,
    schedulesRoomsViewMode,
    setSchedulesRoomsViewMode,
    roomIssues: bookings?.roomIssues ?? dashboardData?.roomIssues ?? [],
    setRoomIssues: bookings?.setRoomIssues ?? dashboardData?.setRoomIssues ?? (() => {}),
    onOpenFacilityLogModal,
    pendingBookings: bookings?.pendingBookings ?? [],
    setPendingBookings: bookings?.setPendingBookings ?? (() => {}),
    pendingSchedules: schedules?.pendingSchedules ?? [],
    handleConfirmBooking: bookings.handleConfirmBooking,
    handleRejectBooking: bookings.handleRejectBooking,
    parseRoomName,
    getFloorColor,
    getAlphabeticalColor,
    formatInstrumentName,
    getAlphabeticalUniColor,
    checkTimeOverlap,
    getPlanDisplayName: schedules?.getPlanDisplayName,

    // Staff & Employees
    campusTeachers: params.campusTeachers ?? staff?.campusTeachers ?? [],
    bypassTeachers: params.bypassTeachers ?? staff?.bypassTeachers ?? [],
    coaches: params.coaches ?? staff?.coaches ?? [],
    allTeachers: params.allTeachers ?? staff?.allTeachers ?? [],
    employees: staff?.employees ?? [],
    setEmployees: staff.setEmployees,
    revealedPins: staff.revealedPins,
    setRevealedPins: staff.setRevealedPins,
    employeeFirstName: staff.employeeFirstName,
    setEmployeeFirstName: staff.setEmployeeFirstName,
    employeeLastName: staff.employeeLastName,
    setEmployeeLastName: staff.setEmployeeLastName,
    employeeSearchQuery: staff.employeeSearchQuery,
    setEmployeeSearchQuery: staff.setEmployeeSearchQuery,
    employeeStatusTab: staff.employeeStatusTab,
    setEmployeeStatusTab: staff.setEmployeeStatusTab,
    employeeFilterRole: staff.employeeFilterRole,
    setEmployeeFilterRole: staff.setEmployeeFilterRole,
    isEmployeeCsvExpanded: staff.isEmployeeCsvExpanded,
    setIsEmployeeCsvExpanded: staff.setIsEmployeeCsvExpanded,
    employeeCsvText: staff.employeeCsvText,
    setEmployeeCsvText: staff.setEmployeeCsvText,
    showAddEmployeeModal: staff.showAddEmployeeModal,
    setShowAddEmployeeModal: staff.setShowAddEmployeeModal,
    dragHoveredEmployeeRole: staff.dragHoveredEmployeeRole,
    setDragHoveredEmployeeRole: staff.setDragHoveredEmployeeRole,
    employeeFilterRoleFocused: staff.employeeFilterRoleFocused,
    setEmployeeFilterRoleFocused: staff.setEmployeeFilterRoleFocused,
    employeeStatusTabFocused: staff.employeeStatusTabFocused,
    setEmployeeStatusTabFocused: staff.setEmployeeStatusTabFocused,
    employeeSearchFocused: staff.employeeSearchFocused,
    setEmployeeSearchFocused: staff.setEmployeeSearchFocused,
    handleCreateEmployee: staff.handleCreateEmployee,
    handleDeleteUser: staff.handleDeleteUser,
    handleImportEmployees: staff.handleImportEmployees,
    handleToggleRole: staff.handleToggleRole,
    handleUpdateEmployeeRole: staff.handleUpdateEmployeeRole,

    // Briefing
    expandedSidebarTeacherId: staff.expandedSidebarTeacherId,
    setExpandedSidebarTeacherId: staff.setExpandedSidebarTeacherId,
    selectedFilterTeacherId: schedules?.selectedFilterTeacherId,
    setSelectedFilterTeacherId: schedules?.setSelectedFilterTeacherId,
    students: studentsHook?.students ?? [],
    userMap: params.userMap ?? dashboardData?.userMap ?? {},
    roomMap: dashboardData?.roomMap ?? {},
    isAvvSigned: params.isAvvSigned ?? settings?.isAvvSigned ?? dashboardData?.isAvvSigned ?? true,
    setShowAvvModal: params.setShowAvvModal ?? settings?.setShowAvvModal ?? dashboardData?.setShowAvvModal ?? (() => {}),
    showLogbookModal: bookings?.showLogbookModal ?? false,
    setShowLogbookModal: bookings?.setShowLogbookModal ?? (() => {}),
    showStorageManagerModal: licenses?.showStorageManagerModal ?? dashboardData?.showStorageManagerModal ?? false,
    setShowStorageManagerModal: licenses?.setShowStorageManagerModal ?? dashboardData?.setShowStorageManagerModal ?? (() => {}),
    dismissedInvoiceAlert: params.dismissedInvoiceAlert ?? dashboardData?.dismissedInvoiceAlert ?? false,
    setDismissedInvoiceAlert: params.setDismissedInvoiceAlert ?? dashboardData?.setDismissedInvoiceAlert ?? (() => {}),
    selectedInvoice: licenses?.selectedInvoice ?? dashboardData?.selectedInvoice ?? null,
    setSelectedInvoice: licenses?.setSelectedInvoice ?? dashboardData?.setSelectedInvoice ?? (() => {}),
    contractStartDate: licenses?.contractStartDate ?? dashboardData?.contractStartDate ?? null,
    simulatedToday: params.simulatedToday ?? dashboardData?.simulatedToday ?? '',
    studentLevyMonthly_global: licenses.studentLevyMonthly_global,
    extraLevyMonthly_global: licenses.extraLevyMonthly_global,
    studentSharePreview_global: licenses.studentSharePreview_global,
    schoolShareBookedExtra_global: licenses.schoolShareBookedExtra_global,
    currentTotalB2B_global: licenses.currentTotalB2B_global,
    mixedTotal_global: licenses.mixedTotal_global,
    fetchLogbookBookings: bookings.fetchLogbookBookings,
    getEffectiveStorageUsedBytes,

    // Crisis Management
    crisisNotifications: crisis.crisisNotifications,
    crisisTabMode: crisis.crisisTabMode,
    setCrisisTabMode: crisis.setCrisisTabMode,
    selectedCrisisTeacherId: crisis.selectedCrisisTeacherId,
    setSelectedCrisisTeacherId: crisis.setSelectedCrisisTeacherId,
    handleMarkAsNotified: crisis.handleMarkAsNotified,
    handleClaimTicket: crisis.handleClaimTicket,
    handleArchiveCrisisTicket: crisis.handleArchiveCrisisTicket,
    handleArchiveAllResolvedTickets: crisis.handleArchiveAllResolvedTickets,
    handleEndAbsenceOnBehalf: crisis.handleEndAbsenceOnBehalf,
    expandedLiveDayStr: crisis.expandedLiveDayStr,
    setExpandedLiveDayStr: crisis.setExpandedLiveDayStr,
    selectedArchiveLog: crisis.selectedArchiveLog,
    setSelectedArchiveLog: crisis.setSelectedArchiveLog,

    // Licenses & Billing
    activeStudentsCount_global: licenses.activeStudentsCount_global,
    activeGroovelabStudentsCount_global: licenses.activeGroovelabStudentsCount_global,
    passiveStudentsCount_global: licenses.passiveStudentsCount_global,
    billableTeachersCount: licenses.billableTeachersCount,
    teacherServiceFeeTotal_global: licenses.teacherServiceFeeTotal_global,
    moduleCost_global: licenses.moduleCost_global,
    storageAddonFee_global: licenses.storageAddonFee_global,
    baseB2B_global: licenses.baseB2B_global,
    masterRates,
    effectiveSchoolRates,
    masterPricing,
    isSammelzahler: licenses.isSammelzahler,
    fetchTariffBookings: licenses.fetchTariffBookings,
    hasCampusSub: licenses.hasCampusSub,
    setHasCampusSub: licenses.setHasCampusSub,
    hasGroovelabSub: licenses.hasGroovelabSub,
    setHasGroovelabSub: licenses.setHasGroovelabSub,
    campusActivatedThisMonth: licenses.campusActivatedThisMonth,
    setCampusActivatedThisMonth: licenses.setCampusActivatedThisMonth,
    groovelabActivatedThisMonth: licenses.groovelabActivatedThisMonth,
    setGroovelabActivatedThisMonth: licenses.setGroovelabActivatedThisMonth,
    handleToggleCampusSub: licenses.handleToggleCampusSub,
    handleToggleGroovelabSub: licenses.handleToggleGroovelabSub,
    studentBillingOption: licenses.studentBillingOption,
    setStudentBillingOption: licenses.setStudentBillingOption,
    isBillingBooked: licenses.isBillingBooked,
    setIsBillingBooked: licenses.setIsBillingBooked,
    bookedExtraUsers: licenses.bookedExtraUsers,
    setBookedExtraUsers: licenses.setBookedExtraUsers,
    extraUsersSliderVal: licenses.extraUsersSliderVal,
    setExtraUsersSliderVal: licenses.setExtraUsersSliderVal,
    extraBillingOption: licenses.extraBillingOption,
    setExtraBillingOption: licenses.setExtraBillingOption,
    nextBillingOption: licenses.nextBillingOption,
    setNextBillingOption: licenses.setNextBillingOption,
    nextBillingOptionEffectiveAt: licenses.nextBillingOptionEffectiveAt,
    setNextBillingOptionEffectiveAt: licenses.setNextBillingOptionEffectiveAt,
    showChangeTariffModal: licenses.showChangeTariffModal,
    setShowChangeTariffModal: licenses.setShowChangeTariffModal,
    showCheckoutModal: licenses.showCheckoutModal,
    setShowCheckoutModal: licenses.setShowCheckoutModal,
    checkoutStep: licenses.checkoutStep,
    setCheckoutStep: licenses.setCheckoutStep,
    billingPayer: licenses.billingPayer,
    setBillingPayer: licenses.setBillingPayer,
    showSuccessModal: licenses.showSuccessModal,
    setShowSuccessModal: licenses.setShowSuccessModal,
    customUmlageAmount: licenses.customUmlageAmount,
    setCustomUmlageAmount: licenses.setCustomUmlageAmount,
    agreedToTerms: licenses.agreedToTerms,
    setAgreedToTerms: licenses.setAgreedToTerms,
    couponCode: licenses.couponCode,
    setCouponCode: licenses.setCouponCode,
    isCouponApplied: licenses.isCouponApplied,
    setIsCouponApplied: licenses.setIsCouponApplied,
    couponDiscount: licenses.couponDiscount,
    setCouponDiscount: licenses.setCouponDiscount,
    showCouponInput: licenses.showCouponInput,
    setShowCouponInput: licenses.setShowCouponInput,
    hasCustomBillingAddress: licenses.hasCustomBillingAddress,
    setHasCustomBillingAddress: licenses.setHasCustomBillingAddress,
    customBillingName: licenses.customBillingName,
    setCustomBillingName: licenses.setCustomBillingName,
    customBillingStreet: licenses.customBillingStreet,
    setCustomBillingStreet: licenses.setCustomBillingStreet,
    customBillingZip: licenses.customBillingZip,
    setCustomBillingZip: licenses.setCustomBillingZip,
    customBillingCity: licenses.customBillingCity,
    setCustomBillingCity: licenses.setCustomBillingCity,
    customBillingEmail: licenses.customBillingEmail,
    setCustomBillingEmail: licenses.setCustomBillingEmail,
    customBillingLeitwegId: licenses.customBillingLeitwegId,
    setCustomBillingLeitwegId: licenses.setCustomBillingLeitwegId,
    hasCustomActivationBillingAddress: licenses.hasCustomActivationBillingAddress,
    setHasCustomActivationBillingAddress: licenses.setHasCustomActivationBillingAddress,
    customActivationBillingName: licenses.customActivationBillingName,
    setCustomActivationBillingName: licenses.setCustomActivationBillingName,
    customActivationBillingStreet: licenses.customActivationBillingStreet,
    setCustomActivationBillingStreet: licenses.setCustomActivationBillingStreet,
    customActivationBillingZip: licenses.customActivationBillingZip,
    setCustomActivationBillingZip: licenses.setCustomActivationBillingZip,
    customActivationBillingCity: licenses.customActivationBillingCity,
    setCustomActivationBillingCity: licenses.setCustomActivationBillingCity,
    customActivationBillingEmail: licenses.customActivationBillingEmail,
    setCustomActivationBillingEmail: licenses.setCustomActivationBillingEmail,
    selectedStorageAddonGb: licenses.selectedStorageAddonGb,
    setSelectedStorageAddonGb: licenses.setSelectedStorageAddonGb,
    selectedStorageAddonFee: licenses.selectedStorageAddonFee,
    setSelectedStorageAddonFee: licenses.setSelectedStorageAddonFee,
    showSwitchBillingModelModal: licenses.showSwitchBillingModelModal,
    setShowSwitchBillingModelModal: licenses.setShowSwitchBillingModelModal,
    selectedSwitchTargetPayer: licenses.selectedSwitchTargetPayer,
    setSelectedSwitchTargetPayer: licenses.setSelectedSwitchTargetPayer,
    showStorageTerminationModal: licenses.showStorageTerminationModal,
    setShowStorageTerminationModal: licenses.setShowStorageTerminationModal,
    agreedToSepa: licenses.agreedToSepa,
    setAgreedToSepa: licenses.setAgreedToSepa,
    showConfirmExtra: licenses.showConfirmExtra,
    setShowConfirmExtra: licenses.setShowConfirmExtra,
    isSchoolTrial: licenses.isSchoolTrial,
    setIsSchoolTrial: licenses.setIsSchoolTrial,
    schoolTrialEndsAt: licenses.schoolTrialEndsAt,
    setSchoolTrialEndsAt: licenses.setSchoolTrialEndsAt,
    schoolStatus: licenses.schoolStatus,
    setSchoolStatus: licenses.setSchoolStatus,
    subscriptionBypass: licenses.subscriptionBypass,
    setContractStartDate: licenses?.setContractStartDate ?? dashboardData?.setContractStartDate ?? (() => {}),
    setSimulatedToday: params.setSimulatedToday ?? dashboardData?.setSimulatedToday ?? (() => {}),
    expandedYears: extendedSettings.expandedYears,
    setExpandedYears: extendedSettings.setExpandedYears,
    isCancelled: licenses.isCancelled,
    setIsCancelled: licenses.setIsCancelled,
    schoolContractEndsAt: licenses.schoolContractEndsAt,
    setSchoolContractEndsAt: licenses.setSchoolContractEndsAt,
    showModuleUpgradeModal: licenses.showModuleUpgradeModal,
    setShowModuleUpgradeModal: licenses.setShowModuleUpgradeModal,
    setUpgradeTargetModule: licenses.setUpgradeTargetModule,
    setShowCancelModal: licenses.setShowCancelModal,
    tariffBookings: licenses.tariffBookings,
    loadingTariffBookings: licenses.loadingTariffBookings,
    activeStudentsModalList: licenses.activeStudentsModalList,
    setActiveStudentsModalList: licenses.setActiveStudentsModalList,
    dunningStatus: extendedSettings.dunningStatus,
    setShowDunningPayModal: extendedSettings.setShowDunningPayModal,

    // Equipment
    schoolEquipment: equipment.schoolEquipment,
    selectedEquipmentRoomId: equipment.selectedEquipmentRoomId,
    setSelectedEquipmentRoomId: equipment.setSelectedEquipmentRoomId,
    equipmentFormName: equipment.equipmentFormName,
    setEquipmentFormName: equipment.setEquipmentFormName,
    equipmentFormQty: equipment.equipmentFormQty,
    setEquipmentFormQty: equipment.setEquipmentFormQty,
    equipmentSaving: equipment.equipmentSaving,
    handleSaveEquipment: equipment.handleSaveEquipment,
    equipmentSearchQuery: equipment.equipmentSearchQuery,
    setEquipmentSearchQuery: equipment.setEquipmentSearchQuery,
    equipmentSortFreeFirst: equipment.equipmentSortFreeFirst,
    setEquipmentSortFreeFirst: equipment.setEquipmentSortFreeFirst,
    dragOverRoomId: equipment.dragOverRoomId,
    setDragOverRoomId: equipment.setDragOverRoomId,
    handleDropInstrumentOnRoom: equipment.handleDropInstrumentOnRoom,
    editingEquipmentGroup: equipment.editingEquipmentGroup,
    setEditingEquipmentGroup: equipment.setEditingEquipmentGroup,
    editGroupName: equipment.editGroupName,
    setEditGroupName: equipment.setEditGroupName,
    editGroupModel: equipment.editGroupModel,
    setEditGroupModel: equipment.setEditGroupModel,
    editGroupLink: equipment.editGroupLink,
    setEditGroupLink: equipment.setEditGroupLink,
    editGroupCoupled: equipment.editGroupCoupled,
    setEditGroupCoupled: equipment.setEditGroupCoupled,
    editGroupQty: equipment.editGroupQty,
    setEditGroupQty: equipment.setEditGroupQty,
    editGroupInstancesData: equipment.editGroupInstancesData,
    setEditGroupInstancesData: equipment.setEditGroupInstancesData,
    handleSaveEquipmentGroup: equipment.handleSaveEquipmentGroup,
    handleDeleteEquipment: equipment.handleDeleteEquipment,
    equipmentNameInputRef: equipment.equipmentNameInputRef,
    equipmentQtyInputRef: equipment.equipmentQtyInputRef,

    // Settings & Master Data
    kioskPinLength: settings.kioskPinLength,
    setKioskPinLength: settings.setKioskPinLength,
    bypassPin: settings.bypassPin,
    setBypassPin: settings.setBypassPin,
    logRetention: settings.logRetention,
    setLogRetention: settings.setLogRetention,
    syncInterval: settings.syncInterval,
    setSyncInterval: settings.setSyncInterval,
    calendarUrls: settings.calendarUrls,
    newCalendarUrlInput: settings.newCalendarUrlInput,
    setNewCalendarUrlInput: settings.setNewCalendarUrlInput,
    lastBackupDate: settings.lastBackupDate,
    schoolYearStartDay: settings.schoolYearStartDay,
    schoolYearStartMonth: settings.schoolYearStartMonth,
    autoDeleteExpiredUsers: settings.autoDeleteExpiredUsers,
    isCurrentDevicePasskeyActive: settings.isCurrentDevicePasskeyActive,
    isSavingSettings: settings.isSavingSettings,
    isSettingsDirty: settings.isSettingsDirty,
    activeSecretarySettingsModal: settings.activeSecretarySettingsModal,
    setActiveSecretarySettingsModal: settings.setActiveSecretarySettingsModal,
    settingsTab: settings.settingsTab,
    setSettingsTab: settings.setSettingsTab,
    showResetModal: settings.showResetModal,
    setShowResetModal: settings.setShowResetModal,
    resetConfirmText: settings.resetConfirmText,
    setResetConfirmText: settings.setResetConfirmText,
    showOwnQrModal: settings.showOwnQrModal,
    setShowOwnQrModal: settings.setShowOwnQrModal,
    copiedSettingsLink: settings.copiedSettingsLink,
    setCopiedSettingsLink: settings.setCopiedSettingsLink,
    copiedSettingsPin: settings.copiedSettingsPin,
    setCopiedSettingsPin: settings.setCopiedSettingsPin,
    copiedKioskLink: settings.copiedKioskLink,
    setCopiedKioskLink: settings.setCopiedKioskLink,
    copiedSchoolLink: settings.copiedSchoolLink,
    setCopiedSchoolLink: settings.setCopiedSchoolLink,
    setIsFeedbackModalOpen,
    setShowDpoIdCardModal,
    setShowDpoPortalModal,
    setQrModalUser,
    handleSaveAllSettings: settings.handleSaveAllSettings,
    handleAddCalendarUrl: settings.handleAddCalendarUrl,
    handleRemoveCalendarUrl: settings.handleRemoveCalendarUrl,
    handleExportBackup: settings.handleExportBackup,
    handleRestoreBackup: settings.handleRestoreBackup,
    handleEnrollBiometrics: settings.handleEnrollBiometrics,
    handleRemoveBiometrics: settings.handleRemoveBiometrics,
    handleTestBiometrics: settings.handleTestBiometrics,
    handleDeleteExpiredStudents: settings.handleDeleteExpiredStudents,
    handleToggleAutoClean: settings.handleToggleAutoClean,
    handleUpdateSchoolYear: settings.handleUpdateSchoolYear,
    biometricsStatus: settings.biometricsStatus,
    biometricsMessage: settings.biometricsMessage,
    kioskToken: extendedSettings.kioskToken,
    isExporting: settings.isExporting,
    isRestoring: settings.isRestoring,

    // Announcements
    announcementsList: announcements.announcementsList,
    announcementsLoading: announcements.announcementsLoading,
    editingAnnouncementId: announcements.editingAnnouncementId,
    setEditingAnnouncementId: announcements.setEditingAnnouncementId,
    newAnnouncementTitle: announcements.newAnnouncementTitle,
    setNewAnnouncementTitle: announcements.setNewAnnouncementTitle,
    newAnnouncementDescription: announcements.newAnnouncementDescription,
    setNewAnnouncementDescription: announcements.setNewAnnouncementDescription,
    newAnnouncementType: announcements.newAnnouncementType,
    setNewAnnouncementType: announcements.setNewAnnouncementType,
    newAnnouncementPriority: announcements.newAnnouncementPriority,
    setNewAnnouncementPriority: announcements.setNewAnnouncementPriority,
    newAnnouncementIsAnonymous: announcements.newAnnouncementIsAnonymous,
    setNewAnnouncementIsAnonymous: announcements.setNewAnnouncementIsAnonymous,
    newAnnouncementTargetType: announcements.newAnnouncementTargetType,
    setNewAnnouncementTargetType: announcements.setNewAnnouncementTargetType,
    newAnnouncementTargetGroup: announcements.newAnnouncementTargetGroup,
    setNewAnnouncementTargetGroup: announcements.setNewAnnouncementTargetGroup,
    newAnnouncementTargetTeacherId: announcements.newAnnouncementTargetTeacherId,
    setNewAnnouncementTargetTeacherId: announcements.setNewAnnouncementTargetTeacherId,
    newAnnouncementDueDate: announcements.newAnnouncementDueDate,
    setNewAnnouncementDueDate: announcements.setNewAnnouncementDueDate,
    newAnnouncementRecurrence: announcements.newAnnouncementRecurrence,
    setNewAnnouncementRecurrence: announcements.setNewAnnouncementRecurrence,
    newAnnouncementAttachmentUrl: announcements.newAnnouncementAttachmentUrl,
    setNewAnnouncementAttachmentUrl: announcements.setNewAnnouncementAttachmentUrl,
    newAnnouncementQuestions: announcements.newAnnouncementQuestions,
    setNewAnnouncementQuestions: announcements.setNewAnnouncementQuestions,
    isUploadingAnnouncementAttachment: announcements.isUploadingAnnouncementAttachment,
    handleUploadAnnouncementAttachment: announcements.handleUploadAnnouncementAttachment,
    handleSaveAnnouncement: announcements.handleCreateAnnouncement,
    handleDeleteAnnouncement: announcements.handleDeleteAnnouncement,
    selectedAnnouncementForStats: announcements.selectedAnnouncementForStats,
    setSelectedAnnouncementForStats: announcements.setSelectedAnnouncementForStats,
    announcementResponsesList: announcements.announcementResponsesList,
    fetchAnnouncementStats: announcements.fetchAnnouncementStats,
    statsModalTab: announcements.statsModalTab,
    setStatsModalTab: announcements.setStatsModalTab,
    statsStatusFilter: announcements.statsStatusFilter,
    setStatsStatusFilter: announcements.setStatsStatusFilter,
    statsSearchQuery: announcements.statsSearchQuery,
    setStatsSearchQuery: announcements.setStatsSearchQuery,
    expandedResponseIds: announcements.expandedResponseIds,
    setExpandedResponseIds: announcements.setExpandedResponseIds,
    handleExportCSV: announcements.handleExportCSV,

    // Audit Logs
    auditLogs: audit.auditLogs,
    auditLoading: audit.auditLoading,
    auditSearchQuery: audit.auditSearchQuery,
    setAuditSearchQuery: audit.setAuditSearchQuery,
    auditActionFilter: audit.auditActionFilter,
    setAuditActionFilter: audit.setAuditActionFilter,
    auditLimit: audit.auditLimit,
    setAuditLimit: audit.setAuditLimit,
    exportAuditLogsToCsv: audit.exportAuditLogsToCsv,
    translateKey: audit.translateKey,
    translateValue: audit.translateValue,
    gdprRequests: audit.gdprRequests,
    gdprLoading: audit.gdprLoading,
    completeGdprRequest: audit.completeGdprRequest,
    rejectGdprRequest: audit.rejectGdprRequest
  };
}
