/**
 * 🏛️ Campus-Groovelab VdM-Katalog (0,1% Goldstandard)
 * vdmDrumScoreSnippets.ts
 * 
 * Autarker Satellit für die 6 kanonischen VdM-Schlagzeugübungen im PAS-Standard.
 * Kapselt Notendaten zur Einhaltung des 1.500-Zeilen-Budgets im Hauptkatalog.
 */

import { MicroScoreSnippet } from '../components/student/meisterwerk/microscore/microScore.types';

export const VDM_DRUM_SCORE_SNIPPETS: MicroScoreSnippet[] = [
  {
    id: 'vdm-drum-rock-beat-8th',
    title: 'Rock-Groove 4/4 (Standard 8tel)',
    category: 'Rhythmus',
    vdmFolder: 'grooves',
    vdmLevel: 'unterstufe',
    instrument: 'drums',
    clef: 'percussion',
    timeSignature: '4/4',
    tempoBpm: 90,
    barsCount: 2,
    displayMode: 'notes',
    description: 'VdM Unterstufe 1: Der universelle 8tel Rock-Groove. Durchgehender Hi-Hat-Puls (G5), Bass Drum auf 1 & 3 (F4) und Snare-Backbeat auf 2 & 4 (C5).',
    tags: ['Schlagzeug', 'Rock-Beat', 'Groove', 'PAS-Notation', 'Backbeat'],
    isVdmStandard: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    authorRole: 'teacher',
    notes: [
      { id: 'vdr0_hh0', barIndex: 0, beatFraction: 0, duration: '8', pitch: 'G5' },
      { id: 'vdr0_bd0', barIndex: 0, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'vdr0_hh2', barIndex: 0, beatFraction: 2, duration: '8', pitch: 'G5' },
      { id: 'vdr0_hh4', barIndex: 0, beatFraction: 4, duration: '8', pitch: 'G5' },
      { id: 'vdr0_sd4', barIndex: 0, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'vdr0_hh6', barIndex: 0, beatFraction: 6, duration: '8', pitch: 'G5' },
      { id: 'vdr0_hh8', barIndex: 0, beatFraction: 8, duration: '8', pitch: 'G5' },
      { id: 'vdr0_bd8', barIndex: 0, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'vdr0_hh10', barIndex: 0, beatFraction: 10, duration: '8', pitch: 'G5' },
      { id: 'vdr0_hh12', barIndex: 0, beatFraction: 12, duration: '8', pitch: 'G5' },
      { id: 'vdr0_sd12', barIndex: 0, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'vdr0_hh14', barIndex: 0, beatFraction: 14, duration: '8', pitch: 'G5' },
      { id: 'vdr1_hh0', barIndex: 1, beatFraction: 0, duration: '8', pitch: 'G5' },
      { id: 'vdr1_bd0', barIndex: 1, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'vdr1_hh2', barIndex: 1, beatFraction: 2, duration: '8', pitch: 'G5' },
      { id: 'vdr1_hh4', barIndex: 1, beatFraction: 4, duration: '8', pitch: 'G5' },
      { id: 'vdr1_sd4', barIndex: 1, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'vdr1_hh6', barIndex: 1, beatFraction: 6, duration: '8', pitch: 'G5' },
      { id: 'vdr1_hh8', barIndex: 1, beatFraction: 8, duration: '8', pitch: 'G5' },
      { id: 'vdr1_bd8', barIndex: 1, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'vdr1_hh10', barIndex: 1, beatFraction: 10, duration: '8', pitch: 'G5' },
      { id: 'vdr1_hh12', barIndex: 1, beatFraction: 12, duration: '8', pitch: 'G5' },
      { id: 'vdr1_sd12', barIndex: 1, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'vdr1_hh14', barIndex: 1, beatFraction: 14, duration: '8', pitch: 'G5' }
    ]
  },
  {
    id: 'vdm-drum-four-on-floor',
    title: 'Four-on-the-Floor (Disco-Pulse)',
    category: 'Rhythmus',
    vdmFolder: 'grooves',
    vdmLevel: 'unterstufe',
    instrument: 'drums',
    clef: 'percussion',
    timeSignature: '4/4',
    tempoBpm: 116,
    barsCount: 2,
    displayMode: 'notes',
    description: 'VdM Unterstufe 2: Vier Viertel Kick (F4) pro Takt mit Snare-Backbeat (C5) und Offbeat-Hi-Hat (G#5) für Dance- und Pop-Feeling.',
    tags: ['Disco', 'Four-on-the-Floor', 'Pop', 'Dance', 'Hi-Hat-Offbeat'],
    isVdmStandard: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    authorRole: 'teacher',
    notes: [
      { id: 'fof0_bd0', barIndex: 0, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'fof0_hh0', barIndex: 0, beatFraction: 0, duration: '8', pitch: 'G5' },
      { id: 'fof0_hh2', barIndex: 0, beatFraction: 2, duration: '8', pitch: 'G#5' },
      { id: 'fof0_bd4', barIndex: 0, beatFraction: 4, duration: '4', pitch: 'F4' },
      { id: 'fof0_sd4', barIndex: 0, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'fof0_hh4', barIndex: 0, beatFraction: 4, duration: '8', pitch: 'G5' },
      { id: 'fof0_hh6', barIndex: 0, beatFraction: 6, duration: '8', pitch: 'G#5' },
      { id: 'fof0_bd8', barIndex: 0, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'fof0_hh8', barIndex: 0, beatFraction: 8, duration: '8', pitch: 'G5' },
      { id: 'fof0_hh10', barIndex: 0, beatFraction: 10, duration: '8', pitch: 'G#5' },
      { id: 'fof0_bd12', barIndex: 0, beatFraction: 12, duration: '4', pitch: 'F4' },
      { id: 'fof0_sd12', barIndex: 0, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'fof0_hh12', barIndex: 0, beatFraction: 12, duration: '8', pitch: 'G5' },
      { id: 'fof0_hh14', barIndex: 0, beatFraction: 14, duration: '8', pitch: 'G#5' },
      { id: 'fof1_bd0', barIndex: 1, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'fof1_hh0', barIndex: 1, beatFraction: 0, duration: '8', pitch: 'G5' },
      { id: 'fof1_hh2', barIndex: 1, beatFraction: 2, duration: '8', pitch: 'G#5' },
      { id: 'fof1_bd4', barIndex: 1, beatFraction: 4, duration: '4', pitch: 'F4' },
      { id: 'fof1_sd4', barIndex: 1, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'fof1_hh4', barIndex: 1, beatFraction: 4, duration: '8', pitch: 'G5' },
      { id: 'fof1_hh6', barIndex: 1, beatFraction: 6, duration: '8', pitch: 'G#5' },
      { id: 'fof1_bd8', barIndex: 1, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'fof1_hh8', barIndex: 1, beatFraction: 8, duration: '8', pitch: 'G5' },
      { id: 'fof1_hh10', barIndex: 1, beatFraction: 10, duration: '8', pitch: 'G#5' },
      { id: 'fof1_bd12', barIndex: 1, beatFraction: 12, duration: '4', pitch: 'F4' },
      { id: 'fof1_sd12', barIndex: 1, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'fof1_hh12', barIndex: 1, beatFraction: 12, duration: '8', pitch: 'G5' },
      { id: 'fof1_hh14', barIndex: 1, beatFraction: 14, duration: '8', pitch: 'G#5' }
    ]
  },
  {
    id: 'vdm-drum-tom-fill-in',
    title: '8tel Tom-Fill & Crash-Akzent',
    category: 'Rhythmus',
    vdmFolder: 'grooves',
    vdmLevel: 'mittelstufe',
    instrument: 'drums',
    clef: 'percussion',
    timeSignature: '4/4',
    tempoBpm: 85,
    barsCount: 2,
    displayMode: 'notes',
    description: 'VdM Mittelstufe 1: Koordination Kessel & Becken. Takt 1 solider Groove, Takt 2 dynamisches Fill-In: Snare (C5) -> High Tom (E5) -> Mid Tom (D5) -> Floor Tom (A4).',
    tags: ['Fill-In', 'Toms', 'Crash', 'Dynamik', 'Mittelstufe'],
    isVdmStandard: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    authorRole: 'teacher',
    notes: [
      { id: 'fil0_bd0', barIndex: 0, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'fil0_hh0', barIndex: 0, beatFraction: 0, duration: '8', pitch: 'G5' },
      { id: 'fil0_hh2', barIndex: 0, beatFraction: 2, duration: '8', pitch: 'G5' },
      { id: 'fil0_sd4', barIndex: 0, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'fil0_hh4', barIndex: 0, beatFraction: 4, duration: '8', pitch: 'G5' },
      { id: 'fil0_hh6', barIndex: 0, beatFraction: 6, duration: '8', pitch: 'G5' },
      { id: 'fil0_bd8', barIndex: 0, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'fil0_hh8', barIndex: 0, beatFraction: 8, duration: '8', pitch: 'G5' },
      { id: 'fil0_hh10', barIndex: 0, beatFraction: 10, duration: '8', pitch: 'G5' },
      { id: 'fil0_sd12', barIndex: 0, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'fil0_hh12', barIndex: 0, beatFraction: 12, duration: '8', pitch: 'G5' },
      { id: 'fil0_hh14', barIndex: 0, beatFraction: 14, duration: '8', pitch: 'G5' },
      { id: 'fil1_sd0', barIndex: 1, beatFraction: 0, duration: '8', pitch: 'C5' },
      { id: 'fil1_sd2', barIndex: 1, beatFraction: 2, duration: '8', pitch: 'C5' },
      { id: 'fil1_th4', barIndex: 1, beatFraction: 4, duration: '8', pitch: 'E5' },
      { id: 'fil1_th6', barIndex: 1, beatFraction: 6, duration: '8', pitch: 'E5' },
      { id: 'fil1_tm8', barIndex: 1, beatFraction: 8, duration: '8', pitch: 'D5' },
      { id: 'fil1_tm10', barIndex: 1, beatFraction: 10, duration: '8', pitch: 'D5' },
      { id: 'fil1_tf12', barIndex: 1, beatFraction: 12, duration: '8', pitch: 'A4' },
      { id: 'fil1_tf14', barIndex: 1, beatFraction: 14, duration: '8', pitch: 'A4' }
    ]
  },
  {
    id: 'vdm-drum-offbeat-hihat',
    title: 'Offbeat Hi-Hat Groove (Reggae / Ska)',
    category: 'Rhythmus',
    vdmFolder: 'grooves',
    vdmLevel: 'unterstufe',
    instrument: 'drums',
    clef: 'percussion',
    timeSignature: '4/4',
    tempoBpm: 100,
    barsCount: 2,
    displayMode: 'notes',
    description: 'VdM Unterstufe 2: Unabhängigkeit der Extremitäten. Geöffnete Hi-Hat (G#5) auf allen Und-Zählzeiten (1+, 2+, 3+, 4+) über Kick & Snare.',
    tags: ['Offbeat', 'Reggae', 'Ska', 'Unabhängigkeit', 'Hi-Hat'],
    isVdmStandard: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    authorRole: 'teacher',
    notes: [
      { id: 'ob0_bd0', barIndex: 0, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'ob0_hh2', barIndex: 0, beatFraction: 2, duration: '8', pitch: 'G#5' },
      { id: 'ob0_sd4', barIndex: 0, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'ob0_hh6', barIndex: 0, beatFraction: 6, duration: '8', pitch: 'G#5' },
      { id: 'ob0_bd8', barIndex: 0, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'ob0_hh10', barIndex: 0, beatFraction: 10, duration: '8', pitch: 'G#5' },
      { id: 'ob0_sd12', barIndex: 0, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'ob0_hh14', barIndex: 0, beatFraction: 14, duration: '8', pitch: 'G#5' },
      { id: 'ob1_bd0', barIndex: 1, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'ob1_hh2', barIndex: 1, beatFraction: 2, duration: '8', pitch: 'G#5' },
      { id: 'ob1_sd4', barIndex: 1, beatFraction: 4, duration: '4', pitch: 'C5' },
      { id: 'ob1_hh6', barIndex: 1, beatFraction: 6, duration: '8', pitch: 'G#5' },
      { id: 'ob1_bd8', barIndex: 1, beatFraction: 8, duration: '4', pitch: 'F4' },
      { id: 'ob1_hh10', barIndex: 1, beatFraction: 10, duration: '8', pitch: 'G#5' },
      { id: 'ob1_sd12', barIndex: 1, beatFraction: 12, duration: '4', pitch: 'C5' },
      { id: 'ob1_hh14', barIndex: 1, beatFraction: 14, duration: '8', pitch: 'G#5' }
    ]
  },
  {
    id: 'vdm-drum-funk-pocket-16th',
    title: '16tel Funk Pocket & Synkopen',
    category: 'Rhythmus',
    vdmFolder: 'grooves',
    vdmLevel: 'mittelstufe',
    instrument: 'drums',
    clef: 'percussion',
    timeSignature: '4/4',
    tempoBpm: 78,
    barsCount: 2,
    displayMode: 'notes',
    description: 'VdM Mittelstufe 2: Mikrotiming und Pocket. Durchgehende 16tel-Hi-Hat mit synkopierten Bass-Drum-Kicks auf den "e"- und "a"-Sechzehnteln.',
    tags: ['Funk', '16tel', 'Pocket', 'Synkopen', 'Timing'],
    isVdmStandard: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    authorRole: 'teacher',
    notes: [
      { id: 'fk0_bd0', barIndex: 0, beatFraction: 0, duration: '8', pitch: 'F4' },
      { id: 'fk0_hh0', barIndex: 0, beatFraction: 0, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh1', barIndex: 0, beatFraction: 1, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh2', barIndex: 0, beatFraction: 2, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh3', barIndex: 0, beatFraction: 3, duration: '16', pitch: 'G5' },
      { id: 'fk0_sd4', barIndex: 0, beatFraction: 4, duration: '8', pitch: 'C5' },
      { id: 'fk0_hh4', barIndex: 0, beatFraction: 4, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh5', barIndex: 0, beatFraction: 5, duration: '16', pitch: 'G5' },
      { id: 'fk0_bd6', barIndex: 0, beatFraction: 6, duration: '16', pitch: 'F4' },
      { id: 'fk0_hh6', barIndex: 0, beatFraction: 6, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh7', barIndex: 0, beatFraction: 7, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh8', barIndex: 0, beatFraction: 8, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh9', barIndex: 0, beatFraction: 9, duration: '16', pitch: 'G5' },
      { id: 'fk0_bd10', barIndex: 0, beatFraction: 10, duration: '16', pitch: 'F4' },
      { id: 'fk0_hh10', barIndex: 0, beatFraction: 10, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh11', barIndex: 0, beatFraction: 11, duration: '16', pitch: 'G5' },
      { id: 'fk0_sd12', barIndex: 0, beatFraction: 12, duration: '8', pitch: 'C5' },
      { id: 'fk0_hh12', barIndex: 0, beatFraction: 12, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh13', barIndex: 0, beatFraction: 13, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh14', barIndex: 0, beatFraction: 14, duration: '16', pitch: 'G5' },
      { id: 'fk0_hh15', barIndex: 0, beatFraction: 15, duration: '16', pitch: 'G5' },
      { id: 'fk1_bd0', barIndex: 1, beatFraction: 0, duration: '8', pitch: 'F4' },
      { id: 'fk1_hh0', barIndex: 1, beatFraction: 0, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh1', barIndex: 1, beatFraction: 1, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh2', barIndex: 1, beatFraction: 2, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh3', barIndex: 1, beatFraction: 3, duration: '16', pitch: 'G5' },
      { id: 'fk1_sd4', barIndex: 1, beatFraction: 4, duration: '8', pitch: 'C5' },
      { id: 'fk1_hh4', barIndex: 1, beatFraction: 4, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh5', barIndex: 1, beatFraction: 5, duration: '16', pitch: 'G5' },
      { id: 'fk1_bd6', barIndex: 1, beatFraction: 6, duration: '16', pitch: 'F4' },
      { id: 'fk1_hh6', barIndex: 1, beatFraction: 6, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh7', barIndex: 1, beatFraction: 7, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh8', barIndex: 1, beatFraction: 8, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh9', barIndex: 1, beatFraction: 9, duration: '16', pitch: 'G5' },
      { id: 'fk1_bd10', barIndex: 1, beatFraction: 10, duration: '16', pitch: 'F4' },
      { id: 'fk1_hh10', barIndex: 1, beatFraction: 10, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh11', barIndex: 1, beatFraction: 11, duration: '16', pitch: 'G5' },
      { id: 'fk1_sd12', barIndex: 1, beatFraction: 12, duration: '8', pitch: 'C5' },
      { id: 'fk1_hh12', barIndex: 1, beatFraction: 12, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh13', barIndex: 1, beatFraction: 13, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh14', barIndex: 1, beatFraction: 14, duration: '16', pitch: 'G5' },
      { id: 'fk1_hh15', barIndex: 1, beatFraction: 15, duration: '16', pitch: 'G5' }
    ]
  },
  {
    id: 'vdm-drum-halftime-ballad',
    title: 'Halftime Heavy Rock & Balladen-Puls',
    category: 'Rhythmus',
    vdmFolder: 'grooves',
    vdmLevel: 'unterstufe',
    instrument: 'drums',
    clef: 'percussion',
    timeSignature: '4/4',
    tempoBpm: 72,
    barsCount: 2,
    displayMode: 'notes',
    description: 'VdM Unterstufe 2: Weites Raumgefühl. Ride-Becken (F5) auf 8teln, Kick auf 1 und 3+, und Snare nur auf Schlag 3 (Halftime Feel).',
    tags: ['Halftime', 'Ballade', 'Ride', 'Heavy-Rock', 'Time-Feeling'],
    isVdmStandard: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    authorRole: 'teacher',
    notes: [
      { id: 'ht0_bd0', barIndex: 0, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'ht0_rd0', barIndex: 0, beatFraction: 0, duration: '8', pitch: 'F5' },
      { id: 'ht0_rd2', barIndex: 0, beatFraction: 2, duration: '8', pitch: 'F5' },
      { id: 'ht0_rd4', barIndex: 0, beatFraction: 4, duration: '8', pitch: 'F5' },
      { id: 'ht0_rd6', barIndex: 0, beatFraction: 6, duration: '8', pitch: 'F5' },
      { id: 'ht0_sd8', barIndex: 0, beatFraction: 8, duration: '4', pitch: 'C5' },
      { id: 'ht0_rd8', barIndex: 0, beatFraction: 8, duration: '8', pitch: 'F5' },
      { id: 'ht0_bd10', barIndex: 0, beatFraction: 10, duration: '8', pitch: 'F4' },
      { id: 'ht0_rd10', barIndex: 0, beatFraction: 10, duration: '8', pitch: 'F5' },
      { id: 'ht0_rd12', barIndex: 0, beatFraction: 12, duration: '8', pitch: 'F5' },
      { id: 'ht0_rd14', barIndex: 0, beatFraction: 14, duration: '8', pitch: 'F5' },
      { id: 'ht1_bd0', barIndex: 1, beatFraction: 0, duration: '4', pitch: 'F4' },
      { id: 'ht1_rd0', barIndex: 1, beatFraction: 0, duration: '8', pitch: 'F5' },
      { id: 'ht1_rd2', barIndex: 1, beatFraction: 2, duration: '8', pitch: 'F5' },
      { id: 'ht1_rd4', barIndex: 1, beatFraction: 4, duration: '8', pitch: 'F5' },
      { id: 'ht1_rd6', barIndex: 1, beatFraction: 6, duration: '8', pitch: 'F5' },
      { id: 'ht1_sd8', barIndex: 1, beatFraction: 8, duration: '4', pitch: 'C5' },
      { id: 'ht1_rd8', barIndex: 1, beatFraction: 8, duration: '8', pitch: 'F5' },
      { id: 'ht1_bd10', barIndex: 1, beatFraction: 10, duration: '8', pitch: 'F4' },
      { id: 'ht1_rd10', barIndex: 1, beatFraction: 10, duration: '8', pitch: 'F5' },
      { id: 'ht1_rd12', barIndex: 1, beatFraction: 12, duration: '8', pitch: 'F5' },
      { id: 'ht1_rd14', barIndex: 1, beatFraction: 14, duration: '8', pitch: 'F5' }
    ]
  }
];
