/**
 * Central Single Source of Truth (SSOT) for all Legal, Pricing, and Business Model Wording
 * Platform: Campus-Groovelab
 * Compliance: § 535 BGB (SaaS), DSGVO Art. 28 (AVV), UWG § 5 (Abmahnschutz), PAngV, § 14/19 UStG,
 *             UrhDaG § 1 Abs. 2, DSA Art. 6/11/16, BFSG 2025, BSG B 12 R 3/20 R
 */

export const LEGAL_MASTER_WORDING = {
  // Plattform-Name
  platformName: 'Campus-Groovelab',

  // 1. Software-Bereitstellung (0,00 € Inklusive)
  softwareProvisioning: {
    title: 'Software-Bereitstellung',
    canonicalLineItem: 'Campus-Groovelab Software-Bereitstellung',
    priceText: '0,00 € (Inklusive)',
    onboardingInfo: 'Software-Bereitstellung: 0,00 € (Inklusive). Keine Einrichtungsgebühr. Modul-Auswahl (Campus & GrooveLab) flexibel im Dashboard wählbar.',
    noLicenseFeeDisclaimer: 'Keine gesonderten Lizenzkaufgebühren. Berechnet wird ausschließlich die gemietete Cloud- und Hosting-Infrastruktur.',
    noLicenseFeeShort: 'Keine Lizenzkaufgebühren (0,00 €)',
    slogan: 'Transparentes Cloud-Hosting statt teurer Software-Lizenzen',
    unifiedSaasContract: 'Software-as-a-Service (SaaS)-Bereitstellung nach § 535 BGB: Bereitstellung der Software ohne Lizenzkaufgebühr (0,00 € Einrichtungsgebühr), Abrechnung erfolgt rein über die modulare Cloud-Infrastruktur.'
  },

  // 2. Modulare Buchung & Cloud-Hosting
  hosting: {
    campus: {
      name: 'Modul Campus',
      canonicalLineItem: 'Cloud- & Datenbank-Hosting: Modul Campus',
      priceText: '14,90 € / Mo. (DE/AT) • CHF 19.90 / Mo. (CH)',
      priceEur: '14,90 € / Mo.',
      priceChf: 'CHF 19.90 / Mo.',
      description: 'Stundenplan, Hausaufgabenheft, Schüler-Protokoll & Raum-Engine'
    },
    groovelab: {
      name: 'Modul GrooveLab',
      canonicalLineItem: 'Cloud- & Datenbank-Hosting: Modul GrooveLab',
      priceText: '9,90 € / Mo. (DE/AT) • CHF 14.90 / Mo. (CH)',
      priceEur: '9,90 € / Mo.',
      priceChf: 'CHF 14.90 / Mo.',
      description: 'Bands, Songs, Repertoire, Live Lab & Skill-Radar'
    },
    bundle: {
      name: 'Kombi-Vorteil Bündel',
      canonicalLineItem: 'Kombi-Vorteilsrabatt (Infrastruktur-Bündel)',
      savingsText: '-4,90 € / Mo. (DE/AT) • -4.90 CHF / Mo. (CH)',
      bundlePriceText: '19,90 € / Mo. (DE/AT) • CHF 29.90 / Mo. (CH)',
      description: 'Campus & GrooveLab gemeinsam gebucht (Sie sparen 4,90 € / CHF 4.90 / Mo.)'
    },
    modularityClaim: 'Campus und GrooveLab sind modular und unabhängig voneinander nach individuellem Bedarf buchbar.'
  },

  // 3. Service- & Betreuungsgebühren
  fees: {
    staffServiceFee: 'Service- & Administrationspauschale: 0,49 € / Mo. (DE/AT) bzw. CHF 1.00 / Mo. (CH) je aktive Lehrkraft (Verwaltung & Schulleitung 0,00 € / CHF 0.00 inklusive)',
    studentBaseFee: 'Basis-Bereitstellung: 0,09 € / Mo. (DE/AT) bzw. CHF 0.20 / Mo. (CH) je Schüler (QR-Landingpage, Stundenplan & DSGVO/nDSG-Hosting)',
    studentCampusFee: 'Cloud- & Modul-Bereitstellung Campus: 0,49 € / Mo. (DE/AT) bzw. CHF 1.00 / Mo. (CH) je aktiver Schüler',
    studentGroovelabFee: 'Cloud- & Modul-Bereitstellung GrooveLab: 0,49 € / Mo. (DE/AT) bzw. CHF 1.00 / Mo. (CH) je aktiver Schüler (immer 100% von der Schule übernommen)',
    directBillingAnnualOnly: 'Schüler-Direktabrechnungen mit Eltern/Schülern (B2C-Verbrauchervertrag) erfolgen ausnahmslos als einmaliger, befristeter Jahresbeitrag (max. 11 × 0,49 € = 5,39 € inkl. USt. in DE/AT bzw. 11 × CHF 1.00 = CHF 11.00 in CH pro Schuljahr) – niemals als monatliches Abonnement. Die Bereitstellung endet automatisch mit Schuljahresende ohne Kündigungserfordernis (keine Abofalle). Zu Beginn jedes neuen Schuljahres (September) sowie bei Neuanmeldung ist der erste Monat für alle Schüler erneut zu 100 % kostenfrei (Probemonat). Wird danach kein neuer Jahresbeitrag geleistet, fällt das Profil automatisch und unterbrechungsfrei auf die Basis-Bereitstellung (0,09 € / Mo. bzw. CHF 0.20 / Mo.) zurück, deren Kosten vollumfänglich von der Musikschule getragen werden (Stundenplan, Raum & Identität bleiben zu 100 % erhalten; kein Datenverlust, keine Schuldenfalle). Das gesetzliche Widerrufsrecht richtet sich nach § 356 Abs. 5 BGB (Erlöschen bei sofortiger Nutzungsausführung mit ausdrücklicher Zustimmung).',
    hardshipQuotaFloorRule: 'Härtefall-Freikontingent & 20er-Staffel (Eltern-Direktabrechnung): Erreicht eine Musikschule im Modell der Eltern-Direktabrechnung mindestens 20 aktivierte Vollzahler-Profile, stellt Campus-Groovelab für jeweils volle 20 aktivierte Schüler je einen kostenfreien Härtefall-Platz (0,00 €) zur Verfügung. Bruchteile unterhalb von 20 Vollzahlern begründen keinen Anspruch (strikte kaufmännische Abrundung: floor(n / 20)). Der Stichtag zur Feststellung des Kontingents ist der 1. Oktober (nach Ablauf des kostenfreien Probemonats September). Sinkt die Zahl der Vollzahler im Folgejahr, werden überzählige Härtefall-Profile nahtlos über die B2B-Rechnung der Schule zum regulären Schülerbeitrag (0,49 € / Mo. bzw. max. 5,39 € Einmalbeitrag / Schuljahr) als Träger-Überhang weitergeführt, sofern die Schule die Profile nicht vor dem Stichtag aktiv auf den Basistarif (0,09 € / Mo.) zurückstuft. Ein Ausschluss oder eine Stigmatisierung von Schülern findet zu keinem Zeitpunkt statt.'
  },

  // 4. Rechtshinweise & AGB
  legalDisclaimers: {
    onboardingConsent: 'Mit Klick auf „Kostenfrei freischalten“ akzeptieren Sie unsere AGB für Bildungseinrichtungen sowie die Vereinbarung zur Auftragsverarbeitung (AVV nach Art. 28 DSGVO / Art. 9 nDSG). Die AVV steht Ihnen jederzeit vorab zur dauerhaften Speicherung und als signierte PDF-Fassung zur Verfügung.',
    b2bContractNature: 'Software-as-a-Service (SaaS)-Mietvertrag gemäß § 535 ff. BGB (DE) / §§ 1090 ff. ABGB (AT) / Art. 253 ff. OR (CH) über schlüsselfertige Cloud-Infrastruktur.',
    pedagogicalAddonDisclaimer: 'Pädagogischer Add-On-Charakter & Subsidiaritäts-Grundsatz: Campus-Groovelab ist ein didaktisches Zusatz-, Erleichterungs- und Übermittlungswerkzeug („Convenience-Tool / Fast-Track-Option“) zur Beschleunigung und Erleichterung des Musikschulalltags. Die Plattform ersetzt ausdrücklich kein behördliches oder amtliches Schulverwaltungssystem (ERP-Software wie iMikel, MSVplus oder Musikschul-Manager) und stellt zu keinem Zeitpunkt den ausschließlichen oder verbindlich vorgeschriebenen Dienst-, Weisungs- oder Kommunikationskanal der Musikschule dar.',
    subsidiarityAndConvenienceDoctrine: 'Pädagogischer Add-On-Charakter & Subsidiaritäts-Grundsatz: Campus-Groovelab ist ein didaktisches Zusatz-, Erleichterungs- und Übermittlungswerkzeug („Convenience-Tool / Fast-Track-Option“) zur Beschleunigung und Erleichterung des Musikschulalltags. Die Plattform ersetzt ausdrücklich kein behördliches oder amtliches Schulverwaltungssystem (ERP-Software wie iMikel, MSVplus oder Musikschul-Manager) und stellt zu keinem Zeitpunkt den ausschließlichen oder verbindlich vorgeschriebenen Dienst-, Weisungs- oder Kommunikationskanal der Musikschule dar.',
    primaryChannelsAndReservationUnderReserve: 'Primärwege, Weisungsautonomie der Schule, Vorbehalt & Wahlfreiheit: Die offizielle dienstrechtliche Kommunikation, verbindliche Arbeitsanweisungen der Schulleitung sowie die hoheitliche Verwaltung von Schüler- und Honorarstammdaten verbleiben vollumfänglich auf den herkömmlichen Primärkanälen der Musikschule (dienstliche E-Mail, interne Kommunikationssysteme wie MS Teams, Telefon, behördliche ERP-Software oder Aushang). Lehrkräfte und Mitarbeiter sind zu jedem Zeitpunkt berechtigt, Stundenpläne, Raumwünsche und Terminänderungen alternativ auf dem herkömmlichen Weg (per E-Mail oder telefonisch) an das Sekretariat zu übermitteln. Raumbuchungsanfragen, Stundenplanübermittlungen und Terminabstimmungen in der Plattform stellen unverbindliche Voranfragen („unter Vorbehalt“) bzw. technische Botenübermittlungen dar; sie begründen zu keinem Zeitpunkt eine automatische Buchungsgarantie oder rechtsgeschäftliche Bindungswirkung für das Raum- und Stundenkontingent der Musikschule. Die verbindliche Zuteilung und Einpflege in das amtliche Schul-ERP obliegt allein der Schulleitung bzw. dem Schulsekretariat. Die Datenüberführung in das amtliche Verwaltungssystem der Schule obliegt der Musikschule.',
    emergencyFallbackDisclaimer: 'Bei technischen Störungen oder Ausfällen läuft der Schulbetrieb uneingeschränkt über herkömmliche Wege (Telefon, E-Mail) weiter (Ausschluss von Unterrichtsausfall-Haftung).',
    kleinunternehmerUStG19: 'In DE gemäß § 19 UStG bzw. in AT gemäß § 6 Abs. 1 Z 27 UStG 1994 umsatzsteuerbefreit (Kleinunternehmerregelung). In der Schweiz gilt Leistungsort Schweiz (nicht im Inland steuerbar gem. Art. 8 Abs. 1 MWSTG).',
    standardVatGrandfathering: 'Alle angegebenen Entgelte verstehen sich für die Dauer des bestehenden Vertrags als garantierte Endpreise (Bruttopreisgarantie für Bestandskunden). Tritt der Betreiber von der Kleinunternehmerregelung (§ 19 UStG) zur Regelbesteuerung (19 % MwSt.) über, bleibt der tatsächliche Zahlbetrag für bestehende Verträge centgenau unverändert; die gesetzliche Mehrwertsteuer gilt in diesem Fall als im bisherigen Entgelt vollständig enthalten. In der Schweiz gilt Leistungsort Schweiz (nicht im Inland steuerbar gem. Art. 8 Abs. 1 MWSTG).',
    deterministicDspNonAiAct: 'Deterministische Signalverarbeitung & Ausschluss von KI-Systemen (VO (EU) 2024/1689 ErwGr. 12 & Art. 3 Nr. 1): Sämtliche didaktischen Audio-Werkzeuge (CampusTuner Stimmgerät, Metronom, Loopstation) sowie der 15-Stufen-Stundenplan-Solver basieren auf rein deterministischen mathematischen Algorithmen (Fast-Fourier-Transformation, Autokorrelation, Constraint-Satisfaction-Heuristiken). Es kommen keine adaptiven oder probabilistischen maschinellen Lernverfahren (Deep Learning, neuronale Netze) zum Einsatz. Eine automatisierte Entscheidungsfindung oder Profilbildung (§ 22 DSGVO) findet nicht statt; menschliche Lehrkräfte und Schulleitungen behalten die uneingeschränkte Letztentscheidung.',
    screenlessPractice: 'Didaktisches Prinzip des bildschirmfreien Übens (Screenless Practice): Im Modus „Von Eltern geführt“ verbleibt das Endgerät bei den Erziehungsberechtigten. Übezeiten am akustischen Instrument werden per 1-Klick-Quittierung verbucht, um Kinder (insbesondere 6–9 Jahre) vor verfrühter Bildschirmzeit zu schützen (einheitliche elterliche Freigabe bis 16 Jahre in DE, AT und CH).',
    twoStageScheduleAndRoomModel: 'Zweistufige Stundenplan- und Raumdisposition (Herrenberg-Compliance & kommunale Raumhoheit): Lehrkräfte stimmen Unterrichtstermine autonom mit Schülern ab und übermitteln den fertigen Stundenplan als pädagogischen Vorschlagsentwurf ohne eigenmächtige Raumwahl an das Schulsekretariat. Das Schulsekretariat prüft den Entwurf auf Vereinbarkeit mit den Raumressourcen und weist der Lehrkraft nach pflichtgemäßem Ermessen einen freien Unterrichtsraum zu. Erst mit Raumzuweisung und Freigabe durch das Sekretariat erlangt der Stundenplan organisatorische Gültigkeit.',
    herrenbergCompliance: 'Autonomie von Honorarlehrkräften & Übermittlungsfreiheit (BSG B 12 R 3/20 R & § 7a SGB IV): Stundenplan- und Terminabstimmungen stellen unverbindliche didaktische Dispositionsvorschläge dar. Der Abstimmungsprozess erfolgt nach dem zweiseitigen Ressourcenmodell: Lehrkräfte stimmen Unterrichtszeiten didaktisch mit Schülern ab und übermitteln unverbindliche Entwürfe ohne Raumfestlegung; das Schulsekretariat prüft die Raumressource und weist der Lehrkraft einen freien Raum zu (keine hoheitliche Terminzuteilung). Lehrkräften (insbesondere freien Honorarkräften) steht es vollkommen frei, Stundenpläne digital über Campus-Groovelab einzureichen oder auf herkömmlichem Weg (per E-Mail, Telefon oder Zettel) an die Schulverwaltung zu übermitteln. Die Nutzung der Plattform ist freiwillig; es besteht kein Gerätezuteilungs- oder App-Nutzungszwang. Die Plattform übt keine Weisungs- oder Kontrollfunktion aus, ist kein Arbeitszeiterfassungsinstrument, führt keine automatisierte Leistungs- oder Verhaltenskontrolle (§ 87 BetrVG / BPersVG) durch und wahrt das Recht auf Nichterreichbarkeit (§ 5 ArbSchG).',
    didacticFreedomMethodology: 'Didaktische Methodenfreiheit & Ausschluss erzwungener Curricula (§ 7 SGB IV / BSG B 12 R 3/20 R): Lehrkräfte (insbesondere freie Honorarkräfte) sind in der Wahl ihrer Lehrmethoden, der didaktischen Literatur, Songauswahl und Unterrichtsgestaltung frei. Die Plattform erteilt keine verbindlichen Lernziel- oder Lehrplanvorgaben; Notizen, Repertoires und Skill-Radare fungieren als rein persönliche pädagogische Hilfsmittel der Lehrkraft.',
    voluntarySubstitutionsNotice: 'Freiwilligkeit von Vertretungen & didaktisches Nachhol-System (§ 7 SGB IV / § 611a BGB): Die Übernahme von Unterrichtsvertretungen für abwesende Kollegen erfolgt ausnahmslos auf freiwilliger Basis ohne arbeitsrechtliche Sanktionen. Bei eigenen Unterrichtsausfällen wahrt das integrierte Token-Nachholsystem (Makeup Tokens) die persönliche Schüler-Lehrer-Beziehung; die Zuweisung fremder Vertretungskräfte verbleibt im Ermessen der Schulverwaltung außerhalb der Plattform.',
    zeroPayrollDoctrine: 'Strikte ERP-Trennung & Zero-Payroll Doktrin (§ 266a StGB / § 7 SGB IV): Campus-Groovelab ist ein reines didaktisches Übe- und Kommunikationswerkzeug und berechnet zu keinem Zeitpunkt Honoraransprüche, Lohnzahlungen oder Auszahlungsbeträge für Lehrkräfte. Die finanzielle Abrechnung und sozialversicherungsrechtliche Beurteilung verbleibt vollumfänglich in den amtlichen Verwaltungssystemen (ERP) der Schulträger.',
    nonParticipationConferences: 'Freiwilligkeit von Konferenzen & Dienstbesprechungen (BSG B 12 R 3/20 R): Freie Honorarlehrkräfte unterliegen über die Plattform keiner Verpflichtung zur Teilnahme an Lehrerkonferenzen, Fachschaftssitzungen oder schulischen Gesamtveranstaltungen. Anwesenheitsnachweise für Dienstbesprechungen werden über die Plattform nicht geführt.',
    byodDeviceFreedom: 'Freiheit zur Gerätenutzung (BYOD) & Ausschluss von Hardware-Zwang (§ 7 SGB IV): Die Plattform ist als browserbasierte PWA vollständig betriebssystem- und geräteagnostisch. Freie Lehrkräfte sind berechtigt, private Endgeräte (Smartphones, Tablets, Laptops) nach eigenem Ermessen zu nutzen; es besteht weder ein Zwang zu behördlichen Dienstgeräten noch zu Mobile-Device-Management (MDM) Überwachungsprofilen.',
    noPaidHolidayClauses: 'Ausschluss von Ferienvergütungs- & Durchbezahlungsklauseln (BSG B 12 R 3/20 R / § 2 EntgFG): Vereinbarungen über die Vergütung von Dozententätigkeiten unterliegen den gesonderten Verträgen zwischen Schulträger und Lehrkraft. Die Plattform enthält und unterstützt keine Klauseln zur pauschalen Durchbezahlung unterrichtsfreier Ferienzeiten für Honorarkräfte.',
    nonExclusivityMultiSchoolFreedom: 'Ausschluss von Wettbewerbs- und Nebentätigkeitsverboten (§ 7 SGB IV / Art. 12 GG): Dozenten sind ausdrücklich berechtigt, an mehreren Musikschulen, allgemeinbildenden Schulen oder privat Unterricht zu erteilen. Die Plattform unterstützt Multi-Schul-Tätigkeiten ohne Konkurrenzverbote oder vertragliche Bindungsmechanismen.',
    herrenbergStatusAttestationBasis: 'Rechtsgrundlage des forensischen Statusnachweises (BSG B 12 R 3/20 R & § 7a / § 28p SGB IV): Das im Court-Proof Exportmodul generierte forensische Dossier dokumentiert für Statusfeststellungsverfahren der Deutschen Rentenversicherung gerichtsverwertbar die tatsächliche Ausgestaltung des Unterrichtsbetriebs (Dispositionsautonomie, 0 Weisungen, 0 Zeiterfassung, 0 Stechuhren, 2-Stufen-Raummodell).',
    staffCouncilNonSurveillance: 'Ausschluss von Leistungs- und Verhaltenskontrolle (§ 87 Abs. 1 Nr. 6 BetrVG / LPVG): Die Plattform erfasst, vergleicht und aggregiert keine Daten zur Überwachung des Verhaltens oder der Arbeitsleistung von Lehrkräften. Schulleitungen und Administratoren haben keinen Zugriff auf individuelle Frequenz- oder Leistungsauswertungen.',
    noTeacherPerformanceTracking: 'Ausschluss von Lehrer-Aktivitäts-Dashboards & Leistungsüberwachung (§ 87 Abs. 1 Nr. 6 BetrVG / LPVG): Schulleitung und Administration haben technisch keinen Einblick in Login-Häufigkeiten, Verweildauern, Antwortzeiten im Chat oder didaktische Frequenzen einzelner Lehrkräfte. Vergleichende Lehrer-Rankings oder Aktivitäts-Scores sind architektonisch ausgeschlossen.',
    asynchronousCommunicationNotice: 'Asynchronitäts-Garantie & Schutz der Wochenendruhe (§ 5 ArbZG / § 5 ArbSchG): Shouts und Direktnachrichten sind rein asynchrone Mitteilungen. Für Lehrkräfte besteht an Samstagen, Sonn- und Feiertagen sowie während der Quiet Hours keinerlei Verpflichtung zur Kenntnisnahme oder Beantwortung von Nachrichten. Aus einer verzögerten Reaktion entstehen keinerlei dienstrechtliche Nachteile.',
    maxWorkTimeAdvisoryNotice: 'Höchstarbeitszeit-Transparenz & Schutz vor Überlastung (§ 3 ArbZG): Überschreitet die geplante Unterrichtszeit an einem Kalendertag 8 Stunden (480 Minuten), weist das System unverbindlich auf gesetzliche Ausgleichs- und Ruhezeiten hin. Bei freien Honorarkräften verbleibt die Dispositionsautonomie unberührt.',
    staffCouncilReportNeutrality: 'Neutralität des forensischen Tätigkeitsberichts (§ 80 Abs. 2 BetrVG): Der zur Dokumentation der Unterrichtsorganisation generierte Tätigkeitsbericht liefert ausschließlich aggregierte Schulgesamtzahlen ohne individuelles Mitarbeiter-Profiling.',
    psychologicalRiskAssessmentDisclaimer: 'Gefährdungsbeurteilung digitaler Medien (§ 5, § 6 ArbSchG / DGUV Information 211-042): Die Plattform stellt mit automatisierten Quiet Hours, dem Ausschluss von Lesebestätigungen, Screenless Practice und 0-Leistungsüberwachung integrierte Schutzfaktoren gegen digitale Fehlbelastung und Arbeitsdruck bereit.',
    b2bMediationAndArbitration: 'Vorgerichtliche Streitbeilegung & Schlichtung (B2B): Bei Streitigkeiten aus oder im Zusammenhang mit diesem Vertrag verpflichten sich die Parteien, vor Beschreitung des ordentlichen Rechtswegs ein strukturiertes Schlichtungsverfahren nach der Schlichtungsordnung der zuständigen Industrie- und Handelskammer (IHK) durchzuführen.',
    privateByDefaultLeaderboards: 'Schutz vor Bloßstellung & Peer-Druck (Private by Default): Übe-Fortschritte, Streaks und XP verbleiben standardmäßig strikt privat beim einzelnen Schüler. Klassen- oder schulweite Vergleiche sind standardmäßig deaktiviert und erfordern die bewusste Freigabe durch die Erziehungsberechtigten.',
    zeroSheetMusicUploadPolicy: 'Vollständiger Ausschluss von Noten-Uploads & Noten-Sharing (§ 1 Abs. 2 UrhDaG): Die Plattform stellt zu keinem Zeitpunkt Funktionen zum Hochladen, Speichern, Teilen oder Verbreiten von Noten, Notenblättern, Partituren oder Noten-PDFs bereit. Jegliches Teilen von Noten-Dateien ist technisch ausgeschlossen und untersagt. Aufgaben verweisen ausschließlich auf bibliografische Metadaten (Titel, Lehrwerk, Seitenzahlen) zur Nutzung mit legal im Handel erworbenen Druckwerken.',
    zeroPhotoPolicy: 'Zero-Photo-Doktrin & Ausschluss privater Bild-Uploads (§ 22 KUG / Art. 25 DSGVO): Auf der Plattform existiert für Schüler und Erziehungsberechtigte keinerlei Möglichkeit zum Hochladen oder Veröffentlichen von Porträtfotos oder privaten Bilddateien. Schülerprofile nutzen ausnahmslos stilisierte Musiker-Avatare zum Schutz der Privatsphäre Minderjähriger.',
    pureMetadataDoctrine: 'Reine Metadaten-Architektur, Bereichsausnahme UrhDaG & Schüler-Übungsaufnahmen (§ 1 Abs. 2 UrhDaG / § 53 Abs. 1, § 60a UrhG DE / § 42f UrhG AT / Art. 19 URG CH / Art. 6, 11 & 16 DSA): Die Plattform speichert und hostet keine geschützten Noten-PDFs oder kommerziellen Notensätze, sondern verarbeitet ausschließlich freie bibliografische Metadaten sowie lizenzierte Links zu externen Medien- (Spotify, YouTube) und autorisierten Notenpartnern (Tomplay). Campus-Groovelab ist kein Diensteanbieter für das Teilen von Online-Inhalten gem. § 2 UrhDaG, sondern ein geschlossener Cloud-Dienst für Bildungszwecke. Im Rahmen des Unterrichts gehostete Schüler-Übungsaufnahmen (z. B. Cover-Versionen geübter Stücke) dienen ausschließlich der individuellen didaktischen Rückmeldung und dem Teilen im geschlossenen privaten Kreis der Familie (§ 53 Abs. 1 UrhG). Keine öffentliche Wiedergabe und keine eigene Vergütungspflicht gegenüber GEMA, AKM oder SUISA. Gesetzliche Kontaktstelle gem. Art. 11/12 DSA: legal@campus-groovelab.de.',
    pinShareLinkFamilyOnly: 'PIN-geschützte Freigabelinks ausschließlich für den privaten Familienkreis (§ 53 Abs. 1 UrhG vs. § 19a UrhG): Soweit die Plattform PIN-geschützte Freigabelinks für Audio-Playlists oder Archiv-Exporte bereitstellt, dürfen diese ausschließlich im engsten Familien- und Verwandtenkreis genutzt werden. Das Teilen in sozialen Netzwerken oder öffentlichen Foren ist urheberrechtlich strengstens untersagt.',
    gamificationNonMonetary: 'Didaktik-Gamification & Punkte-Ausschluss (DSA Art. 25 & § 3 GlüStV): Didaktik-Match, Schüler-Lehrer-Blindtipp, XP-Punkte, Streaks und Sticker dienen rein der spielerischen Gehörbildung und didaktischen Motivation (kein Glücksspiel gem. § 3 GlüStV). XP-Punkte und Sticker besitzen keinen Geld- oder Vermögenswert, sind nicht übertragbar und verfallen bei Vertragsende ersatzlos.',
    facilityManagementExclusion: 'Raum- & Sachmängel-Kaskade (Ausschluss von Facility Management & Verkehrssicherungspflichten): Funktionen zur Dokumentation von Raum- oder Inventarschäden sowie Quittierungen („behoben“) stellen ein rein internes didaktisch-organisatorisches Notizwerkzeug dar. Die Plattform ersetzt kein behördliches CAFM. Verkehrssicherungspflichten (§ 823 BGB) verbleiben vollumfänglich beim Schulträger.',
    contactedStatusDocumentationOnly: 'Rechtsnatur der 1-Tap Kontaktdokumentation („Erreicht“): Soweit Lehrkräfte im Ausfallmanagement die telefonische Kontaktaufnahme per 1-Tap als „Erreicht“ quittieren, handelt es sich um eine rein interne pädagogische Dokumentationsnotiz ohne gesetzliche Zugangsfiktion gem. § 130 BGB.',
    liveLabRemoteLogoutPolicy: 'Live-Lab Steuerung & administrative Session-Beendigung: Das Schulsekretariat ist berechtigt, verwaiste oder überzogene Übesessions an Raum-Terminals remote zu beenden (Remote-Logout), um einen gerechten Übebetrieb an Schul-Terminals sicherzustellen.',
    b2bLiabilityCap: 'BGH-konforme B2B-Haftungshöchstgrenze & Enthaftung (§ 307 BGB): Die verschuldensunabhängige Garantiehaftung für anfängliche Mängel (§ 536a Abs. 1 Alt. 1 BGB / § 1096 ABGB / Art. 259a OR) ist vollumfänglich ausgeschlossen. Die Haftung des Betreibers für einfache Fahrlässigkeit bei Verletzung wesentlicher Vertragspflichten (Kardinalpflichten) ist auf den bei Vertragsschluss typischerweise vorhersehbaren Schaden begrenzt, maximal jedoch auf den Betrag der für 12 Vertragsmonate vereinbarten Netto-Vergütung (mindestens jedoch das 12-Fache des monatlichen Entgelts bzw. 1.000,00 €, höchstens 10.000,00 € bzw. CHF 10.000,00). Die vorstehenden Haftungsbeschränkungen gelten nicht bei Verletzung von Leben, Körper oder Gesundheit, bei Vorsatz oder grober Fahrlässigkeit sowie bei Ansprüchen nach dem Produkthaftungsgesetz. Der Betreiber unterhält zur Absicherung von Groß- und Cyberrisiken eine gewerbliche IT-Vermögensschaden- und Cyber-Haftpflichtversicherung mit einer Deckungssumme von mindestens 2.000.000,00 €.',
    limitationPeriod12Months: '12-monatige Verjährungsverkürzung (B2B): Vertragliche Gewährleistungs- und Schadensersatzansprüche des Kunden verjähren nach 12 Monaten ab gesetzlichem Verjährungsbeginn. Ausgenommen hiervon sind Ansprüche wegen Vorsatz, grober Fahrlässigkeit oder Verletzung von Leben, Körper oder Gesundheit sowie Ansprüche nach dem Produkthaftungsgesetz.',
    dataBackupMitverschulden: 'Mitverschuldensklausel & Datenwiederherstellung (§ 254 BGB): Für den Verlust von Daten haftet der Betreiber der Höhe nach nur insoweit, als der Schaden auch bei ordnungsgemäßer und regelmäßiger Datensicherung durch den Kunden bzw. über die integrierte 1-Klick-Schaltfläche „Export“ für das didaktische Hausaufgaben- und Übe-Protokoll eingetreten wäre (beschränkt auf den typischen Wiederherstellungsaufwand aus regulären Server-Backups).',
    contractTermSchoolYear: 'Vertragslaufzeit & Kündigungsharmonisierung: Verträge für Bildungseinrichtungen laufen grundsätzlich synchron zum Schuljahr (12 Monate bis zum 31. August) und sind mit einer Frist von 3 Monaten zum Schuljahresende (31. Mai) kündbar (Verlängerung um jeweils 12 Monate). Das gesetzliche Recht zur außerordentlichen Kündigung aus wichtigem Grund (§ 314 BGB) bleibt unberührt.',
    userContentIndemnity: 'Urheberrechts-Freistellungsanspruch (Hold-Harmless für Nutzer-Inhalte): Die Musikschule trägt die alleinige rechtliche Verantwortung für alle von ihren Lehrkräften, Mitarbeitern oder Schülern hochgeladenen, verlinkten oder geteilten Noten, Notizen, Audio-Aufnahmen oder Kommunikationsinhalte und stellt den Betreiber von allen begründeten Ansprüchen Dritter (insbesondere von Urhebern, Verlagen und Verwertungsgesellschaften wie GEMA, AKM, SUISA) sowie anfallenden notwendigen Rechtsverteidigungskosten frei.',
    pedagogicalNonSuccessDisclaimer: 'Pädagogischer Enthaftungsschild (Keine Erfolgsgarantie): Der Betreiber stellt rein technische Hilfsmittel und didaktische Werkzeuge (Übe-Timer, Loopstation, Gamification, Notenständer-Modus) bereit. Die didaktische Unterrichtsgestaltung, der persönliche Lernerfolg, Noten, Prüfungsergebnisse und die tatsächliche Beherrschung von Instrumenten verbleiben in der ausschließlichen pädagogischen Verantwortung von Musikschule, Lehrkraft und Schüler.',
    avvInternalIndemnity: 'AVV-Freistellung im Innenverhältnis (Art. 82 DSGVO / Art. 54 nDSG): Der Auftraggeber (Musikschule) stellt den Auftragnehmer im Innenverhältnis von sämtlichen zivilrechtlichen Ansprüchen Dritter (insbesondere von Betroffenen, Schülern oder Eltern nach Art. 82 DSGVO) sowie – soweit gesetzlich zulässig – von behördlichen Verbandsgeldbußen und Rechtsverteidigungskosten frei, die daraus resultieren, dass der Auftraggeber Daten ohne ausreichende Rechtsgrundlage verarbeitet, unzulässige Weisungen erteilt oder elterliche Einwilligungen (Art. 8 DSGVO) nicht ordnungsgemäß eingeholt hat.',
    standaloneAvvArt28: 'Behördentauglicher Stand-Alone Auftragsverarbeitungsvertrag (AVV gem. Art. 28 DSGVO & nDSG): Vollständiger Vertrag mit Anlage 1 (Datenarten & Betroffene) und Anlage 2 (Technische und organisatorische Maßnahmen gem. Art. 32 DSGVO) für Schulträger und Datenschutzbeauftragte. Vorfallsmeldung des Auftragnehmers bei schwerwiegenden Datenpannen (P1) binnen 24 Stunden (bei sonstigen Vorfällen binnen 48 Stunden) zur Wahrung der 72h-Meldepflicht nach Art. 33 DSGVO.',
    ghostSupportAvvGovernance: 'Technischer Fernsupport, Diagnosezugriff („Ghost Support“) & Revisionssicherheit (Art. 28 DSGVO): Soweit zur Störungsbeseitigung ein administrativer Fernzugriff auf Mandanten der Schule erforderlich ist, erfolgt dieser streng weisungsgebunden, zeitlich minimiert und lückenlos kryptografisch protokolliert im revisionssicheren Audit-Trail (master_audit_trail). Ein unbefugtes Auslesen persönlicher Chats oder vertraulicher Schülerbewertungen ist ausgeschlossen.',
    sla995: 'Service Level Agreement (SLA 99,5 % Verfügbarkeit): Verbindliche B2B-Verfügbarkeitsgarantie im Kalendermonat mit 4-stufiger Störungsklassifizierung (P1–P4), zielbasierten Reaktionszeiten (< 2h für P1) und beitragsfreiem Gratismonate-Kompensationsmodell (1, 2, 3 oder 6 Gratismonate auf das Basishosting) unter vollständigem Ausschluss von Bar-Rückzahlungen (No Cash Value). Strikte Drittwirkungssperre gem. § 328 BGB (keine SLA-Ansprüche für Lehrkräfte oder Schüler/Eltern). Ausgenommen von der Ausfallzeit sind höhere Gewalt, netzseitige Ausfälle Dritter außerhalb des Rechenzentrums sowie reguläre Wartungsarbeiten (werktags 22:00–06:00 Uhr) bei Vorankündigung von 48 Stunden bzw. unaufschiebbare Notfall-Sicherheits-Patches zur Gefahrenabwehr. Harte Ausschlussfrist von 30 Kalendertagen für Kompensationsanträge.',
    childProtectionCode8a: 'Kinderschutz-Leitfaden, Vier-Augen-Prinzip & Netiquette (§ 8a SGB VIII / BKiSchG): Schutz vor digitaler 1:1-Grenzverletzung zwischen Lehrkräften und Minderjährigen durch vollständige Eltern-Transparenz und Ausschluss unüberwachter privater Schüler-zu-Schüler-Chats. Dedizierter Meldekanal kinderschutz@campus-groovelab.de.',
    botenmodellDoctrine: 'Technischer Botenstatus & Subordination unter den Musikschulvertrag: Soweit über die Plattform (insbesondere Terminkalender, Termingekoppelte Shoutbox oder Direktnachrichten) Unterrichtstermine abgesagt, verschoben oder Raumwünsche geäußert werden, agiert die Plattform rein als technischer Übermittlungsbote im Auftrag des jeweiligen Nutzers. Sämtliche vertraglichen Rechte und Pflichten (Honorarpflicht, Nachholansprüche, Entschuldigungsfristen) richten sich ausschließlich nach dem Hauptunterrichtsvertrag zwischen Erziehungsberechtigten bzw. Schülern und der Musikschule. Formelle Kündigungen des Musikschulvertrags können über die Plattform nicht erklärt werden.',
    roomReservationUnderReserve: 'Raumbuchungen unter Vorbehalt & ERP-Subordination: Raumbuchungsanfragen und Belegungswünsche im Raumplaner stellen unverbindliche Voranfragen unter dem ausdrücklichen Vorbehalt der verwaltungsseitigen Freigabe dar. Die Plattform ersetzt kein behördliches Raum- oder ERP-System. Die endgültige Raumzuteilung und rechtsverbindliche Buchung obliegt dem Schulsekretariat durch Einpflege in das amtliche Verwaltungssystem der Musikschule.',
    art9GdprExclusion: 'Ausschluss besonderer Kategorien personenbezogener Daten (Art. 9 DSGVO / Art. 5 lit. c nDSG): Die Erfassung, Speicherung oder Übermittlung von sensiblen Gesundheitsdaten, Attesten oder konkreten medizinischen Diagnosen ist plattformweit untersagt. Mitteilungen über Unterrichtsverhinderungen beschränken sich auf die allgemeine Angabe (z. B. „verhindert“ / „abwesend“) ohne medizinische Detailangaben.',
    bfsgAccessibilityDeclaration: 'Erklärung zur digitalen Barrierefreiheit (BFSG 2025 / BITV 2.0 / WCAG 2.2 AA): Campus-Groovelab ist bestrebt, seine Web- und PWA-Angebote barrierefrei zugänglich zu machen. Der verbindliche Status der Vereinbarkeit ist „teilweise vereinbar“ gemäß § 12a Abs. 6 BGG und § 16 BFSG. Ausgenommen sind auditive Live-Echtzeit-Inhalte und nutzergenerierte Schüler-Audioaufnahmen. Feedback- und Schlichtungsmechanismen stehen im Impressum bereit.',
    generalOperatorLiabilityExclusion: 'Allgemeine Betreiber- & Enthaftungsklausel (BGB § 823 / UrhG § 15 / BImSchG): Der Leistungsumfang von Campus-Groovelab umfasst ausschließlich die in der Leistungsbeschreibung spezifizierten Cloud-Funktionen zur Unterrichtsorganisation, Stundenplanung und didaktischen Übebegleitung. Die Bereitstellung der Software entbindet den Kunden nicht von seinen eigenen gesetzlichen, behördlichen, arbeitsrechtlichen und organisatorischen Betreiber-, Aufsichts-, Verkehrs- und Brandschutzpflichten vor Ort (insb. Hausrecht, Versammlungsstättenrecht, Lärmschutz, Vor-Ort-GEMA-Meldungen bei Konzerten und Unfallverhütungsvorschriften).'
  },

  // 5. Tier-1 Enterprise+ Sicherheits- & Kryptographie-Standards (Banking Goldstandard)
  securityStandards: {
    bffArchitecture: 'Backend-for-Frontend (BFF) Gateway-Architektur mit strikter Trennung von Client und internen Datenbank-Tokens (Zero-Token-Leakage in LocalStorage / SessionStorage).',
    jweSessionEncryption: 'Vollverschlüsselte JWE-Sessions mit AES-256-GCM (A256GCM) und strikten __Host-session Cookies (HttpOnly, Secure, SameSite=Strict, Path=/).',
    proactiveSilentRefresh: 'Proaktive Token-Rotation (Silent Refresh) mit 60s-Schwellenwert für unterbrechungsfreie, sichere Unterrichtssitzungen ohne Client-Zutun.',
    antiCsrfOriginGuard: 'Fail-Closed Anti-CSRF & Origin-Guard mit browser-nativem Sec-Fetch-Site Filtering, Referer-Fallback und Host-Header-Poisoning-Schutz.',
    clientVaultEncryption: 'Hardware-gebundene AES-256-GCM Verschlüsselung für alle lokalen Gerätedaten & PIN-Caches (Web Crypto API).',
    zeroKnowledgeHashing: 'OWASP- & BSI-konformes PBKDF2 Zero-Knowledge Hashing mit 100.000 Runden (SHA-512 / SHA-256) & kryptografischem Salz.',
    registrationGate: 'Kryptografisch geschützter Schulanmeldungszugang mit PBKDF2-HMAC-SHA-512 (100.000 Runden) und progressivem 3-Strike Rate-Limiting.',
    sessionLeasing: 'Zero-Trust Session-Leasing mit hardware-gebundenem Fingerprinting und 1-Click Remote-Logout.',
    immutableAuditLedger: 'Revisionssicheres, manipulationsgeschütztes Audit-Ledger mit kryptografischer SHA-512 / SHA-256 Merkle-Chain (GoBD & DSGVO konform).',
    fido2HardwareProtection: 'FIDO2 / WebAuthn Hardware Passkeys mit kryptografischem Signatur-Zähler zum Schutz vor Klon-Angriffen.',
    dataMinimization: 'Kompromisslose DSGVO-Datenminimierung: Keine Speicherung von SEPA-, Bank- oder Kreditkartendaten, keine E-Mail-Adressen Minderjähriger, automatische Nachnamensmaskierung.',
    voiceBiometricsExclusion: 'Reines didaktisches Audio-Streaming ohne biometrische Stimm-, Sprecher- oder Verhaltensmusteranalysen (Art. 9 DSGVO / Art. 6 nDSG).',
    hostingInfrastructure: 'Ausschließliches Hosting in ISO 27001-zertifizierten deutschen Rechenzentren (Hetzner Online GmbH, Falkenstein/Vogtland & Nürnberg, Deutschland) mit stündlichen verschlüsselten Backups. 100% frei von US-Cloudservern, vollständige Immunität gegen US CLOUD Act und FISA 702 (Schrems II konform).',
    indexedDbAudioVault: 'Lokaler IndexedDB Audio-Tresor (groovelab_audio_vault) für 0ms Offline-Playback und bandbreitenfreie Proberaumnutzung.'
  },

  // 6. DIN 66398 Löschkonzept & 2-Stufen-Statusarchitektur
  din66398Retention: {
    title: 'Kommunales Löschkonzept nach DIN 66398 & Art. 17 DSGVO',
    stage1Active: 'Aktiv (0,49 € / Mo.): Vollständiges Schüler-Dashboard, Fokus-Timer, Meisterwerk-Protokoll, Audio-Loopstation & Schulkommunikation.',
    stage2Passive: 'Basis-Bereitstellung (0,09 € / Mo.): Zugriff auf Stundenplan, Raumzuweisung und QR-Landingpage. Identität & Daten bleiben 100% erhalten.',
    fairPlayInactivityRule: 'Bei mehr als 60 Tagen ohne Login wird das Profil fair-play-konform auf Basis-Bereitstellung (0,09 €) umgestellt (automatischer Kostenschutz für Musikschulen).',
    educationalPortfolioRule: 'Didaktische Bildungsbiografie & Meisterwerk-Dokumentation (reine Metadaten gem. Art. 6 Abs. 1 lit. b DSGVO) bleiben über Schuljahre hinweg (mehrjährig) kumulativ erhalten. Physische Datenlöschung erfolgt erst 30 Tage nach formeller Exmatrikulation.',
    audioSchoolYearRetention: 'Didaktische Audio-Aufnahmen (Hausaufgaben, Übe-Studio & Loopstation) dienen der Dokumentation des individuellen Lernfortschritts über das Ausbildungsjahr (pädagogisches Jahres-Portfolio). Sie verbleiben bis zum Ende des jeweiligen Schuljahres (30. September inklusive Karenzzeit) im geschützten deutschen Cloud-Speicher. Eltern und Lehrkräfte besitzen jederzeitige 1-Klick-Selbstlöschautonomie.'
  },

  // 7. Schweizer Musikschul-Compliance (revDSG, MWSTG Art. 21, VMS-Richtlinien & CHF 0.05 Rappenrundung)
  swissMusicSchoolCompliance: {
    title: 'Schweizer Rechts- & Musikschul-Compliance (revDSG, MWSTG & VMS)',
    revDsgCompliance: 'Vollständige Konformität mit dem Schweizer Datenschutzgesetz (revDSG vom 1. September 2023): Datenübermittlung in die EU (Deutschland) gestützt auf den Angemessenheitsbeschluss des Bundesrats gemäss Art. 16 Abs. 1 revDSG. Schutz von besonders schützenswerten Personendaten (Art. 5 lit. c revDSG) durch strikte Neutralität bei Absenzen und Verzicht auf medizinische Diagnosen. Umfassendes Auskunfts- und Herausgaberecht gemäss Art. 25 und Art. 28 revDSG.',
    mwstgArt21EducationExemption: 'Mehrwertsteuerbefreiung für Bildungsleistungen gemäss Art. 21 Abs. 2 Ziff. 11 MWSTG: Unterrichts- und Ausbildungsleistungen von Musikschulen sowie damit eng verbundene didaktische Zusatzleistungen sind von der Mehrwertsteuer ausgenommen. Rechnungsstellung für Schweizer Musikschulen erfolgt in Schweizer Franken (CHF) ohne Mehrwertsteuerausweis unter Ausweisung der Bildungsbefreiung bzw. UID/MWST-Nummer.',
    rappenrundungRule: 'Kaufmännische Rappenrundung auf 5 Rappen (CHF 0.05) gemäss Art. 30 MWSTV: Endbeträge in Schweizer Franken werden deterministisch auf die nächsten CHF 0.05 gerundet (Math.round(amount * 20) / 20). Rechnungen und Zahlungspläne für Schweizer Mandanten weisen ausschliesslich Beträge mit 0.05-Teilbarkeit aus.',
    vmsGuidelinesAndZgb28: 'Verband Musikschulen Schweiz (VMS) & Persönlichkeitsschutz (Art. 28 ZGB): Semesterweise Laufzeitharmonisierung, Wahrung des Kindeswohls und der Persönlichkeitsrechte Minderjähriger durch Avatar-First-Doktrin ohne Fotoveröffentlichung.'
  },

  // 8. Raumausstattungs-Inventar & ERP-Botenstatus (§ 130 BGB, Ausschluss §§ 535, 598 BGB)
  roomEquipmentAndErpSubsidiarity: {
    title: 'Raumausstattungs-Inventar, Zero-Commerce & ERP-Botenstatus',
    messengerStatusDisclaimer: 'Didaktisches Raumausstattungs-Inventar (BGB § 130 Botenstatus). Diese Übersicht dient der didaktischen Unterrichts- und Stundenplanung vor Ort. Die rechtsverbindliche Bestands-, Inventur- und Vermögensbuchhaltung sowie das Leihwesen obliegen ausschließlich dem Primär-ERP der Musikschule (WinMusik, MBS etc.).',
    zeroRentalAndCommerceDoctrine: 'Hermetischer Ausschluss von Instrumentenverleih, Vermietung, Kauf, Ratenkauf oder Mietkauf (§§ 433, 506, 535, 598 BGB). Über die Plattform werden keinerlei Leihverträge abgeschlossen und keine physischen Gegenstände an Schüler, Eltern oder Dritte überlassen.',
    userEntryWarrantyExclusion: 'Ausschluss jeglicher Gewährleistung und Haftung (§§ 276, 280 BGB) für die Richtigkeit, Vollständigkeit oder Aktualität der von Nutzern oder Schulpersonal erfassten Raumausstattungs- und Gerätedaten. Mängelnotizen stellen unverbindliche interne Orientierungshinweise dar und begründen keine rechtliche Mängelrügenwirkung.'
  },

  // 9. Privatrechtlicher Unterrichtsvertrag & B2C-Abrechnung (BGB §§ 611, 614 / § 286 BGB)
  privateTuitionContractAndInvoicing: {
    title: 'Privatrechtlicher Unterrichtsvertrag & Entgeltabrechnung',
    contractNature: 'Rechtsnatur als privatrechtlicher Unterrichtsvertrag (Dienstvertrag gem. §§ 611 ff. BGB bzw. Mietvertrag gem. § 535 BGB). Die Plattform dient ausschließlich der Organisation und didaktischen Unterstützung privatrechtlicher Unterrichtsverhältnisse zwischen der privaten Musikschule und den Schülern bzw. deren Erziehungsberechtigten.',
    noAdministrativeActs: 'Ausschluss hoheitlicher Verwaltungsakte: Abrechnungen, Monatsbeiträge und Entgeltaufstellungen stellen rein zivilrechtliche Rechnungen und Fälligkeitsmitteilungen dar. Es werden zu keinem Zeitpunkt öffentlich-rechtliche Gebührenbescheide, Leistungsbescheide nach dem Kommunalabgabengesetz (KAG) oder Verwaltungsakte im Sinne des § 35 VwVfG erlassen. Rechtsstreitigkeiten unterliegen der ordentlichen Zivilgerichtsbarkeit (ZPO).',
    b2cInvoiceForm: 'Rechnungen an Privatkunden (B2C) werden verbraucherfreundlich in digitaler Textform (PDF) erteilt (§ 14 Abs. 1 UStG n.F.). Die Bereitstellung strukturierter E-Rechnungen (ZUGFeRD / XRechnung) mit Leitweg-ID erfolgt optional ausschließlich für institutionelle oder kommunale Kooperationspartner (B2G).'
  },

  // 10. Bildung und Teilhabe (BuT) & Stigmatisierungsschutz (SGB II § 28 Abs. 7 / DSGVO Art. 9)
  butNonStigmatizationDoctrine: {
    title: 'Bildung und Teilhabe (BuT) & Stigmatisierungsschutz',
    discretionarySettlement: 'Soweit Schüler oder Erziehungsberechtigte Leistungen für Bildung und Teilhabe (§ 28 Abs. 7 SGB II / § 6b BKGG, Bildungskarten, MünsterlandKarte etc.) in Anspruch nehmen, dient die Plattform dem Sekretariat rein als interne Buchungshilfe zur Verrechnung des Förderzuschusses mit dem zivilrechtlichen Unterrichtsbeitrag.',
    absoluteNonStigmatization: 'Absoluter Stigmatisierungsschutz (Menschenwürde & DSGVO Art. 9): Statusvermerke über BuT-Leistungen, Sozialhilfen oder Härtefallregelungen werden strikt auf die interne Sekretariats- und Rechnungsansicht beschränkt. In Schülerprofilen, Band-Chats, Klassenlisten, Protokollen oder gegenüber anderen Schülern und freien Lehrkräften ist jegliche Kennzeichnung oder Offenlegung eines BuT-Bezugs technisch hermetisch ausgeschlossen.'
  },

  // 11. Raumakustik, Gehörschutz & Lärmschutz-Enthaftung (BGB § 823 / ArbSchG)
  noiseAndAcousticLiabilityExclusion: {
    title: 'Raumakustik, Gehörschutz & Lärmschutz-Enthaftung',
    noDecibelMeasurement: 'Keine messtechnische Schallpegel- oder Lärmüberwachung: Die Plattform ist eine reine Software zur Stunden- und Belegungsplanung und führt keinerlei physikalische oder akustische Schallpegelmessungen in Unterrichtsräumen durch. Raumbezeichnungen und Instrumentenzuordnungen stellen unverbindliche didaktische Notizen dar.',
    onSiteResponsibility: 'Ausschließliche Verantwortung vor Ort (BGB § 823 / ArbSchG): Sämtliche gesetzlichen und arbeitsschutzrechtlichen Pflichten zur Einhaltung von Lärmgrenzwerten, zur Bereitstellung von Gehörschutz sowie zur raumakustischen Eignung (z.B. Nachhallzeiten für Schlagzeug- oder Bläserunterricht) verbleiben vollumfänglich und ausschließlich bei der Leitung der Musikschule und den unterrichtenden Lehrkräften vor Ort.'
  },

  // 12. Primär-ERP Subsidiarität bei Verbandsstatistiken & Fördermitteln (BGB § 130 / DSGVO Art. 89)
  associationStatisticsSubsidiarity: {
    title: 'Primär-ERP Subsidiarität bei Verbandsstatistiken & Fördermitteln',
    primaryErpSoleSourceOfTruth: 'Die Erstellung, Aufbereitung und rechtsverbindliche Übermittlung von offiziellen Verbandsstatistiken (bdfm, VdM, Landesverbände) sowie von Verwendungsnachweisen und Belegen für kommunale oder staatliche Zuwendungen obliegt zu 100 % dem amtlichen Primär-ERP der Musikschule (iMikel, MSVplus, Musikschul-Manager etc.).',
    pedagogicalMetricsOnly: 'Campus-Groovelab ist ein didaktischer Übebegleiter und technischer Bote (§ 130 BGB). Alle in der Plattform generierten Übersichten, Übeminuten-Aggregate und Aktivitätsstatistiken stellen rein interne pädagogische Orientierungsdaten dar und besitzen keinerlei amtliche, beihilferechtliche oder förderstatistische Bindungswirkung. Jegliche Haftung für Abweichungen zu amtlichen Meldungen wird ausdrücklich ausgeschlossen.'
  },

  // 13. Digitale Barrierefreiheit & Didaktische Inklusion (BFSG, BITV 2.0 & WCAG 2.2 AA)
  digitalAccessibilityAndInclusion: {
    title: 'Digitale Barrierefreiheit & Didaktische Inklusion (BFSG, BITV 2.0 & WCAG 2.2 AA)',
    bfsgB2cScopeAndTransitionalLaw: 'Geltungsbereich des Barrierefreiheitsstärkungsgesetzes (BFSG ab 28.06.2025): Für den direkten B2C-Eltern-Checkout (5,39 € / Schuljahr) und die damit verbundene Bereitstellung digitaler Dienste gilt das BFSG uneingeschränkt. Die Plattform verzichtet bewusst auf die Inanspruchnahme von Kleinstunternehmer-Ausnahmen (§ 3 Abs. 2 BFSG), um maximale Rechtssicherheit gegenüber Verbandsklagen (UKlaG / § 3a UWG) zu gewährleisten. Gemäß § 38 Abs. 2 BFSG bleiben vor dem Stichtag geschlossene Verträge bis zum Ende ihrer Laufzeit geschützt.',
    wcag22FocusAndDragInvariants: 'Erweiterte WCAG 2.2 Konformitätsstufe AA Invarianten: Sämtliche interaktiven Elemente garantieren Tastatur-Vollbedienbarkeit (WCAG 2.1.1, tabIndex={0}, Enter/Space) und sichtbare Tastaturfokusringe (WCAG 2.4.7). Gemäß WCAG 2.4.11/12 (Focus Not Obscured) wird das Verdecken fokussierter Elemente durch persistente Menüleisten oder Audio-Player mittels dynamischer Bottom-Clearance ausgeschlossen. Stundenplan- und Organisationsraster bieten für alle Drag-and-Drop-Aktionen eine barrierefreie 2-Klick-Tastatur-Alternative (WCAG 2.5.7). Anmelde- und Registrierungsstrecken verzichten auf kognitive Funktionstests wie CAPTCHAs (WCAG 3.3.8). Marken- und didaktische KPI-Hintergrundfarben bleiben unantastbar; Kontrastparität (>= 4,5:1) wird ausnahmslos über hochkontrastierende Schriftfarben (Slate-900) erzielt.',
    statutoryExceptionsAndAntiWarningStatus: 'Erklärung zur digitalen Barrierefreiheit & Abmahnschutz (§ 14 BFSG / § 7 BITV 2.0 / § 3a UWG): Die Webanwendung deklariert den verbindlichen Status „teilweise vereinbar“. Ausnahmen nach § 16 BFSG / § 12a Abs. 6 BGG umfassen die mathematische Echtzeit-Audiosignalverarbeitung (FFT-Tuner) sowie nutzergenerierte Fremduploads von Dozenten und Schülern. Das Durchsetzungsverfahren ist dual strukturiert: Für privatwirtschaftliche B2C-Verbraucherverträge ist die Marktüberwachungsbehörde des jeweiligen Bundeslandes zuständig; für öffentlich-rechtliche Schulträger die Schlichtungsstelle nach § 16 BGG bzw. den Landes-Behindertengleichstellungsgesetzen (L-BGG).',
    multiSensoryMusicInclusion: 'Multi-Sensorische Musik-Inklusion (UN-BRK Art. 24 / WCAG 4.1.3): Barrierefreie Unterrichtsbegleitung umfasst für hörbeeinträchtigte Schüler ein optisches Metronom mit Takt-1-Farbumschlag und haptische Rhythmus-Vibration via Web Vibration API (navigator.vibrate). Für sehbeeinträchtigte Schüler bietet der Audio-Player WAI-ARIA Slider-Semantik (role="slider", aria-valuetext in Takten und Zeit) sowie akustische Vorzähler (Count-In) und dezente Status-Announcements (aria-live="polite").',
    twoStageEasyToReadArchitecture: '2-Stufen-Dokumentenarchitektur (DSGVO Art. 12 / BITV § 4): Volljuristische BGB- und DSGVO-Texte bilden im Footer und Checkout die autoritative Single Source of Truth (Stufe 1). Im Schülerbereich (junior- und teen-Modus) werden Datenschutz- und Nutzungsrechte didaktisch aufbereitet in Leichter Sprache mit visuellen Symbolen vermittelt (Stufe 2), ohne den rechtlichen Schutzgehalt zu relativieren.'
  },

  // 14. NIS-2, Cyber Resilience Act & Enterprise IT-Sicherheit
  nis2CyberResilienceAndInfrastructure: {
    title: 'NIS-2, Cyber Resilience Act & Enterprise IT-Sicherheit',
    incidentReportingCascade: 'Gestufte 4-Phasen-Vorfallsmeldekaskade (NIS-2 Art. 23 / DSGVO Art. 33 / AVV § 6): Zur Absicherung der 72-Stunden-Meldepflicht der Musikschule gegenüber der Landesdatenschutzbehörde (LfDI) garantiert der Plattformbetreiber eine Frühwarnung binnen maximal 24 Stunden nach Kenntniserlangung mit erster Schadens- und Risikoabschätzung. Binnen maximal 72 Stunden wird ein detaillierter Zwischenbericht inklusive schlüsselfertigem Art.-33-DSGVO-Muster-Meldebogen bereitgestellt. Nach Behebung des Vorfalls erhält die Schule spätestens binnen eines Monats ein vollständiges Abschlussdossier inklusive Root-Cause-Analysis und forensischer Nachweise.',
    cyberResilienceActAndSbom: 'Cyber Resilience Act (CRA / VO (EU) 2024/2847) & Software Supply Chain Governance: Für die gesamte Plattform wird bei jedem Build eine maschinenlesbare Software Bill of Materials (SBOM nach CycloneDX v1.6 und SPDX 3.0 Standard) generiert. Diese wird durch VEX-Dokumente (Vulnerability Exploitability eXchange) ergänzt, um False-Positive-Meldungen für ungenutzte Code-Pfade auszuschließen. Schwachstellen mit einem CVSS-Score >= 7.0 (High/Critical) blockieren die Bereitstellung in der CI/CD-Pipeline zwingend fail-closed. Die Software-Lieferkette wird kryptografisch mit SHA-256 gesiegelt.',
    iso27001SovereignHosting: '100% Deutsches Sovereign-Hosting & US CLOUD Act Immunität (DIN EN ISO/IEC 27001): Sämtliche Datenbanken, Microservices, Audio-Speicher und Backups werden ausnahmslos in ISO-27001-zertifizierten deutschen Rechenzentren der Hetzner Online GmbH (Falkenstein/Vogtland & Nürnberg) betrieben. Durch den vollständigen Verzicht auf US-Hyperscaler und US-Dienstleister besteht vollkommene rechtliche Immunität gegen Zugriffsanordnungen nach dem US CLOUD Act (18 U.S.C. § 2713) und FISA 702 (Schrems II konform). Die Datenübertragung ist auf TLS 1.3 mit PFS und HSTS beschränkt; die Speicherung at-rest erfolgt über LUKS AES-256-XTS.',
    postgreSqlKernelWormImmutability: 'PostgreSQL Kernel WORM-Immutabilität & Merkle-Tree Hash-Chain (§ 202a StGB / DSGVO Art. 32 / § 371a ZPO): Sämtliche Audit-Logs und mandantenbezogene Sicherheitsereignisse werden auf Datenbank-Kernel-Ebene durch den Trigger trg_prevent_master_audit_tampering gegen jede nachträgliche Modifikation (UPDATE / DELETE) fail-closed geschützt. Jeder Log-Eintrag verknüpft kryptografisch den SHA-256-Hash seines Vorgängers (Merkle-Chain), wodurch die vollständige Manipulationsfreiheit und höchste zivilprozessuale Beweiskraft vor Gerichten und Aufsichtsbehörden mathematisch garantiert wird. Applikationsnutzer besitzen keinerlei DDL-Rechte.',
    disasterRecoveryAndTombstones: '3-2-1-1-0 Disaster Recovery & DSGVO Art. 17 Anti-Zombie-Tombstones (ISO 22301 / BSI 200-4): Garantierte Notfallkennzahlen mit RPO <= 60 Minuten und RTO <= 45 Minuten durch stündliche georedundante Backups (Nürnberg nach Falkenstein) mit Age X25519 asymmetrischer Zero-Knowledge-Verschlüsselung und WORM-Snapshots auf isolierten Hetzner Storage Boxes. Zur Abwendung von Zombie-Datensätzen nach Katastrophen-Restores führt das System eine WORM-Tombstone-Reconciliation (SHA-256 Hash der gelöschten User-IDs), die zuvor gelöschte Profile vor Freigabe des Live-Traffics atomar erneut tilgt.'
  },

  // 15. EU AI Act, Finanzaufsicht (ZAG) & DACH-Recht (Schweiz & Österreich)
  euAiActFintechAndDachRegulations: {
    title: 'EU AI Act, Finanzaufsicht (ZAG) & DACH-Recht (Schweiz & Österreich)',
    deterministicDspNonAiAct: 'Deterministische DSP statt Hochrisiko-KI (EU AI Act Anhang III / VO (EU) 2024/1689): Sämtliche akustischen Werkzeuge (chromatischer Tuner, harmonische Akkorderkennung, Tonhöhenanalyse) basieren zu 100 % auf mathematischer digitaler Signalverarbeitung (Fast Fourier Transformation, YIN-Autokorrelation, Goertzel-Filter, modale diatonische Stufengewichtung). Es werden keinerlei neuronale Netze oder Machine Learning eingesetzt. Die Plattform ist kein KI-System nach Art. 3 Nr. 1 EU AI Act und vollständig von den Pflichten für Hochrisiko-KI freigestellt.',
    voiceBiometricsExclusionClause: 'Hermetisches Verbot von Stimm- und Sprecherbiometrie (EU AI Act Art. 5 / DSGVO Art. 9): Audioaufnahmen dienen rein pädagogischem Playback im Unterricht. Die Plattform erstellt zu keinem Zeitpunkt Stimmabdrücke (Voiceprints), Sprecherprofile, Sprecheridentifikationen oder biometrische Emotions- und Stimmungsanalysen an Schülern oder Lehrkräften.',
    humanInTheLoopScheduling: 'Human-in-the-Loop Dispositionskontrolle (DSGVO Art. 22 / EU AI Act Art. 14): Vorschläge zur Stundenplan-, Takt- und Raumbelegung im Scheduler stellen unverbindliche technische Berechnungshilfen dar. Die rechtsverbindliche und pädagogische Dispositions- und Freigabekontrolle verbleibt ausnahmslos beim Menschen (Lehrkraft bzw. Schulsekretariat).',
    zeroMoneyTransitTuitionExclusion: 'Hermetischer Ausschluss des Schulgeld-Zahlungsverkehrs (ZAG § 2 Abs. 1 Nr. 9 / PSD3 / § 63 ZAG): Zahlungen zwischen der Musikschule und den Eltern laufen NIEMALS über Campus-Groovelab. Die Plattform betreibt zu keinem Zeitpunkt Treuhandkonten, Sammelkonten, Escrow-Dienste oder Geldtransit. Sämtliche Unterrichtsgebühren, Honorare, Miet- und Ausfallentgelte verbleiben im direkten Bankenverkehr zwischen Eltern und Schule (unverbindlicher SEPA-XML pain.008 Export). Die Zahlungsströme zur Plattform beschränken sich auf die B2B-SaaS-Miete der Schule (§ 535 BGB) und den optionalen B2C-Software-Jahrespass der Eltern (5,39 € gem. §§ 327 ff. BGB). Vollständige Freistellung von BaFin-Erlaubnispflichten.',
    swissRevDsgAndVmsCompliance: 'Schweizer Datenschutz & VMS-Richtlinien (revDSG / Art. 28 ZGB): Datentransfers in die EU (Deutschland) stützen sich auf den offiziellen Angemessenheitsbeschluss des Schweizer Bundesrats gemäss Art. 16 Abs. 1 revDSG. Der Schutz besonders schützenswerter Personendaten (Art. 5 lit. c revDSG) wird durch strikte Absenzen-Neutralität ohne medizinische Diagnosedaten gewahrt. Einhaltung didaktischer VMS-Rahmenpläne und Persönlichkeitsschutz Minderjähriger.',
    swissMwstgAndRappenrundung: 'Schweizer Bildungsbefreiung & 5-Rappen-Rundung (MWSTG Art. 21 / Art. 30 MWSTV): Bildungsleistungen sind gemäss Art. 21 Abs. 2 Ziff. 11 MWSTG von der Mehrwertsteuer ausgenommen. Alle Rechnungsbeträge in Schweizer Franken werden deterministisch auf die nächsten CHF 0.05 kaufmännisch gerundet (roundToFiveRappen).',
    austrianDsgAndSchoolLawCompliance: 'Österreichischer Verfassungs-Datenschutz & Landesmusikschulrecht (§ 1 DSG / § 42f UrhG-AT): Anerkennung des verfassungsgesetzlichen Datenschutzes (§ 1 DSG Österreich). Didaktische Harmonisierung mit den 4 offiziellen Bildungsstufen (Elementar-, Unter-, Mittel- und Oberstufe) der Landesmusikschulgesetze. Wahrung des Verbots digitaler Notenkopien gemäss § 42f UrhG-AT.',
    austrianRksvCashlessExemption: 'Österreichische RKSV-Bargeldlosigkeit & 7-Jahre-Archivierung (RKSV / § 132 BAO): Vollständige Freistellung von der Registrierkassensicherheitsverordnung (RKSV) durch ausschließliche Bargeldlosigkeit. Revisionssichere Aufbewahrung steuerlicher Buchungsdaten über mindestens 7 Jahre gemäss § 132 BAO (Systemstandard: 10 Jahre).',
    digitalServicesActNoticeAndAction: 'Digital Services Act Jugendschutz & Meldeverfahren (DSA / VO (EU) 2022/2065): Bereitstellung eines niederschwelligen Notice & Action Meldebuttons (Art. 16 DSA) in Schüler- und Band-Chats bei Verstößen oder Mobbing. Vollständiger Verzicht auf verhaltensmanipulierende Dark Patterns, Lootboxen oder In-App-Monetarisierungen im Schülerbereich.',
    saasBusinessSeparationFromTeaching: 'Gewerberechtliche Entflechtung & Verbandsneutralität (GewO § 2 / EStG § 18 / bdfm): Strikte rechtliche und steuerliche Trennung von IT-SaaS-Gewerbebetrieb (§ 14 GewO / § 15 EStG) und freiberuflicher Lehrtätigkeit (§ 18 EStG). Die Plattform vermittelt kein Lehrpersonal und schließt Arbeitsvermittlung (§ 296 SGB III) hermetisch aus.'
  }
} as const;
