ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS street VARCHAR(255);
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS house_number VARCHAR(50);
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS phone_number VARCHAR(100);
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS is_trial BOOLEAN DEFAULT true;
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '30 days');
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'trial';
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS subdomain VARCHAR(255) UNIQUE;
