-- Disable RLS for Band tables to allow MVP operations
ALTER TABLE bands DISABLE ROW LEVEL SECURITY;
ALTER TABLE band_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE band_gigs DISABLE ROW LEVEL SECURITY;
ALTER TABLE band_media DISABLE ROW LEVEL SECURITY;
ALTER TABLE band_song_proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE band_proposal_votes DISABLE ROW LEVEL SECURITY;
