-- ==============================================================================
-- Migration 347: GoBD-Generalumkehr, Belegketten-Sequenzierung & Immutability
-- Standards: OWASP ASVS Level 3 / GoBD § 239 HGB / BMF-Schreiben 2019 / Fail-Closed
-- ==============================================================================

-- 1. Add GoBD Reversal & Sequence Tracking Columns
ALTER TABLE public.school_tariff_bookings
  ADD COLUMN IF NOT EXISTS reversal_of_receipt_number VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS record_hash TEXT DEFAULT NULL;

-- Indexing for rapid reversal audits and sequence checks
CREATE INDEX IF NOT EXISTS idx_school_tariff_bookings_reversal ON public.school_tariff_bookings(reversal_of_receipt_number);
CREATE INDEX IF NOT EXISTS idx_school_tariff_bookings_seq ON public.school_tariff_bookings(school_id, sequence_number DESC);

-- 2. HARDENED IMMUTABILITY TRIGGER (GoBD Radierverbot / Append-Only)
-- Absolutely prevents UPDATE and DELETE on school_tariff_bookings, even for superusers / service_role
CREATE OR REPLACE FUNCTION public.trg_enforce_tariff_booking_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'GoBD Violation (§ 239 Abs. 3 HGB): Buchungsjournal-Einträge sind unveränderbar (Append-Only). Korrekturen müssen als Stornobeleg (Generalumkehr) eingebucht werden.';
    ELSIF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'GoBD Violation (§ 239 Abs. 3 HGB): Physisches Löschen von Buchungsjournal-Einträgen ist streng verboten.';
    END IF;
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_school_tariff_bookings_immutable ON public.school_tariff_bookings;
CREATE TRIGGER trg_school_tariff_bookings_immutable
    BEFORE UPDATE OR DELETE ON public.school_tariff_bookings
    FOR EACH ROW
    EXECUTE FUNCTION public.trg_enforce_tariff_booking_immutability();

-- 3. AUTHORITATIVE RPC: revert_tariff_booking_entry (GoBD Generalumkehr)
CREATE OR REPLACE FUNCTION public.revert_tariff_booking_entry(
    p_booking_id UUID,
    p_reason TEXT DEFAULT 'Storno / Buchungskorrektur gem. GoBD'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog, extensions
AS $$
DECLARE
    v_caller_id UUID := public.get_current_authenticated_user_id();
    v_is_master BOOLEAN := public.is_master_admin();
    v_caller_name TEXT := 'System-Administrator';
    v_orig record;
    v_existing_reversal record;
    v_receipt TEXT;
    v_school_prefix TEXT;
    v_date_part TEXT;
    v_random_part TEXT;
    v_storno_rate NUMERIC(10, 2);
    v_new_storno record;
BEGIN
    -- 1. Authorization
    IF NOT v_is_master THEN
        IF v_caller_id IS NULL THEN
            RAISE EXCEPTION 'Authentifizierung erforderlich.';
        END IF;
        SELECT id, school_id, role, first_name, last_name, nickname
        INTO v_orig
        FROM public.users_raw
        WHERE id = v_caller_id;

        IF v_orig.role NOT IN ('admin', 'secretary') THEN
            RAISE EXCEPTION 'Nur Schulleitung oder Master-Administratoren dürfen Stornobuchungen ausführen.';
        END IF;
        v_caller_name := TRIM(COALESCE(v_orig.first_name, '') || ' ' || COALESCE(v_orig.last_name, ''));
        IF v_caller_name = '' THEN v_caller_name := COALESCE(v_orig.nickname, 'Schulverwaltung'); END IF;
    END IF;

    -- 2. Fetch original booking
    SELECT * INTO v_orig FROM public.school_tariff_bookings WHERE id = p_booking_id;
    IF v_orig.id IS NULL THEN
        RAISE EXCEPTION 'Zu stornierender Buchungsbeleg nicht gefunden.';
    END IF;

    -- Check if this record is already a storno
    IF v_orig.booking_type = 'REVERSAL_STORNO' THEN
        RAISE EXCEPTION 'Ein Stornobeleg kann nicht erneut storniert werden.';
    END IF;

    -- Check if an active storno already exists for this receipt
    SELECT * INTO v_existing_reversal 
    FROM public.school_tariff_bookings 
    WHERE reversal_of_receipt_number = v_orig.receipt_number;

    IF v_existing_reversal.id IS NOT NULL THEN
        RAISE EXCEPTION 'Dieser Beleg (%s) wurde bereits durch Stornobeleg %s neutralisiert.', v_orig.receipt_number, v_existing_reversal.receipt_number;
    END IF;

    -- 3. Generate Storno Receipt Number
    v_school_prefix := UPPER(SUBSTRING(REPLACE(v_orig.school_id::TEXT, '-', ''), 1, 6));
    v_date_part := TO_CHAR(CURRENT_DATE, 'YYMMDD');
    v_random_part := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT), 1, 4));
    v_receipt := 'TB-' || v_school_prefix || '-' || v_date_part || '-STORNO-' || v_random_part;

    v_storno_rate := -1 * ABS(v_orig.total_monthly_rate_net);

    -- 4. Insert Reversal Entry (Append-Only)
    INSERT INTO public.school_tariff_bookings (
        receipt_number,
        school_id,
        booked_by,
        booked_by_name,
        booking_type,
        has_campus_subscription,
        has_groovelab_subscription,
        student_billing_option,
        storage_addon_gb,
        storage_addon_monthly_fee,
        storage_addon_status,
        storage_pending_downgrade_gb,
        storage_pending_effective_date,
        total_monthly_rate_net,
        currency,
        effective_date,
        reversal_of_receipt_number,
        notes,
        meta,
        created_at
    ) VALUES (
        v_receipt,
        v_orig.school_id,
        v_caller_id,
        v_caller_name,
        'REVERSAL_STORNO',
        v_orig.has_campus_subscription,
        v_orig.has_groovelab_subscription,
        v_orig.student_billing_option,
        v_orig.storage_addon_gb,
        -1 * ABS(v_orig.storage_addon_monthly_fee),
        v_orig.storage_addon_status,
        NULL,
        NULL,
        v_storno_rate,
        v_orig.currency,
        CURRENT_DATE,
        v_orig.receipt_number,
        COALESCE(p_reason, 'GoBD-Generalumkehr zu Beleg ' || v_orig.receipt_number),
        jsonb_build_object(
            'original_receipt_number', v_orig.receipt_number,
            'original_booking_type', v_orig.booking_type,
            'original_rate', v_orig.total_monthly_rate_net,
            'reversal_timestamp', timezone('utc'::text, now()),
            'reason', p_reason
        ),
        timezone('utc'::text, now())
    )
    RETURNING * INTO v_new_storno;

    -- 5. Audit Logging (GoBD & OWASP ASVS L3)
    PERFORM public.log_security_event(
        'TARIFF_BOOKING_REVERSED',
        v_caller_id,
        jsonb_build_object(
            'original_receipt_number', v_orig.receipt_number,
            'storno_receipt_number', v_receipt,
            'school_id', v_orig.school_id,
            'storno_amount', v_storno_rate,
            'reason', p_reason
        )
    );

    RETURN jsonb_build_object(
        'success', true,
        'message', 'Stornobeleg erfolgreich erzeugt.',
        'receipt_number', v_receipt,
        'original_receipt_number', v_orig.receipt_number,
        'storno_amount', v_storno_rate
    );
END;
$$;
