-- Add trial, contract, and limits fields to schools table
ALTER TABLE schools ADD COLUMN IF NOT EXISTS is_trial BOOLEAN DEFAULT true;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS contract_ends_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_teachers INTEGER DEFAULT 2;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_students INTEGER DEFAULT 6;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_songs INTEGER DEFAULT 5;
